### ISSUE TITLE
.children('.filter') -- returns array

### ISSUE THREAD

**Issue by simeydotme** [kenwheeler/cash#100]
I expect this to return an `instanceof( cash )` just like `.find()` does.

![image](https://cloud.githubusercontent.com/assets/2817396/14586736/7ef6af10-04d4-11e6-81a5-935616440707.png)

But it actually returns an array which cannot be chained/manipulated.

![image](https://cloud.githubusercontent.com/assets/2817396/14586741/b75adbe2-04d4-11e6-93e7-ab2e1ea798ed.png)

**Comment by shshaw** [comment]
Strange! I'll take a look tomorrow if no one else does.

**Comment by shshaw** [comment]
At a quick glance it may be related to the filter method. Other traversal
methods may be affected.

**Comment by simeydotme** [comment]
I haven't tested all of them... but it was the first (and only) one I ran through the new test suite.
I did try `.find()` out of curiosity; and that was OK.

**Comment by shshaw** [comment]
Yes, this is related to `filter`, and therefore this bug affects `$.fn.filter`, too. `Array.prototype.filter` is being called on the collection, so it returns an array. A simple fix would be to run the results through `cash` or `unique` to make them back into a collection, same as `$.fn.eq`. Starting a pull request...

**Comment by shshaw** [comment]
I'm not sure where the unit testing stands, so feel free to run the filter fix through your new suite and accept the pull request if it's ready.

**Comment by simeydotme** [comment]
Thanks, @shshaw ... I'll run it through as soon as possible :)

**Comment by simeydotme** [comment]
## before
![screenshot 160424 142224](https://cloud.githubusercontent.com/assets/2817396/14765869/24bcd3d6-0a28-11e6-9084-b1480b1b0bbc.png)

## after
![screenshot 160424 142311](https://cloud.githubusercontent.com/assets/2817396/14765868/249785e0-0a28-11e6-9fc6-1c2bf9ed0580.png)

lgtm.

Just one thing, the dist files don't have the correct version number according to the `package.json` :) (https://github.com/kenwheeler/cash/blob/54ef956bf4733fb2b9f99b8614d9bc6060c6c411/dist/cash.js#L3)

**Comment by shshaw** [comment]
Good catch on the version number. I'll fix that.

**Comment by shshaw** [comment]
1.2.1 merged & published.
