### ISSUE TITLE
NPM / Bower

### ISSUE THREAD

**Issue by hultberg** [kenwheeler/cash#101]
Would love cash to be published on `npm` or `bower`

**Comment by shshaw** [comment]
It should be available on NPM as cash-dom
https://www.npmjs.com/package/cash-dom

**Comment by hultberg** [comment]
@shshaw: that should be mentioned in the README, but I don't see an section that is optimal for it.

**Comment by shshaw** [comment]
References to NPM and Bower have been added. Thanks for bringing that to our attention!
