### ISSUE TITLE
Should ES2015 be used and what about a style guide?

### ISSUE THREAD

**Issue by softwarespot** [kenwheeler/cash#107]
Currently the library is mismatched between ES5 syntax and ES2015. Which is the correct standard that should be used? Also, have you thought about adopting a style guide and enforcing as part of the gulp build/test process. I always vote for Airbnb, but jQuery's guide is good too.

**Comment by kenwheeler** [comment]
I have a general preference for staying as ES2015 as possible. I typically use the Walmart eslint config.

**Comment by shshaw** [comment]
Any particular instances you've found of ES5 syntax where it should be ES2015?

**Comment by softwarespot** [comment]
@kenwheeler Okay.
@shshaw: [This](https://github.com/kenwheeler/cash/blob/master/src/core.js#L2) for example should use arrow function OR be a function declaration and not expression.

**Comment by simeydotme** [comment]
I'm confused... I thought ES2015 was about providing syntax and scoping tools for better javascript, not forcing terse-ness upon developers?

**Comment by shshaw** [comment]
There are a few code consistency slips that could be fixed. Stylistically, it's weird to me to have an arrow function that's not a property:

```
noop(){}
isFunction(item){ return typeof item === typeof noop; }

**Comment by fabiospampinato** [comment]
Currently any modern syntax will be transpiled down by babel.

Just be sure that what you're writing doesn't implicitly require a polyfill for older browsers (IE10+), e. g. promises.

Regarding the coding style I don't have a guide or specific linter configuration for you, just read the code and try to write in a similar manner.
