### ISSUE TITLE
How do I access an event within a delegated event handler?

### ISSUE THREAD

**Issue by dominicwhittle** [kenwheeler/cash#112]
How do I access events from a delegated event handler?
In order to `e.preventDefault()` for example.

```
$('.parent').on('click', '.child', function (event) {
     // event === undefined
})
```

**Comment by shshaw** [comment]
This is a bug that's about to be patched. See pull request #109 for more info. I should likely have that merged into the main library today.

**Comment by dominicwhittle** [comment]
Super cool. Let me know when you republish to npm :)
