### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#118]
For another project, I've been using JSDoc syntax to document everything. It [works quite well](https://github.com/shshaw/Canvallax/blob/v2.0.0/src/canvallax.Scene.js#L1), and could potentially[ auto-generate the documentation for us](https://github.com/shshaw/Canvallax/tree/v2.0.0/docs)

I don't think we necessarily need to adopt a fully documentation system, but it would be good to at least start commenting the code. Especially where we might be pulling some [coding gymnastics](https://github.com/kenwheeler/cash/blob/master/src/manipulation.js#L18-L21) that aren't immediately obvious.

**Comment by simeydotme** [comment]
coding gymnastics? that's coding voodoo :P
I'm down for documenting the code :)

**Comment by kenwheeler** [comment]
+1 for JSDoc

**Comment by shshaw** [comment]
[First pass](https://github.com/kenwheeler/cash/blob/jsdoc/src/core.js) at using JSDoc for documenting the core. Is that too much detail? Not enough?

Need to add documentation for `isString` and `isFunction` and the Array prototype methods, but that should be mostly complete for core.js

**Comment by simeydotme** [comment]
looks nice... 
Just as a reference if you've not considered already: https://github.com/lodash/lodash/blob/4.12.0/lodash.js Lodash I'd say is probably best-in-class for docs :)

**Comment by shshaw** [comment]
Good reference, @simeydotme. Hadn't looked through their comments before. Very clean. Looks like they're using JSDoc for tagging as well.

**Comment by kenwheeler** [comment]
This shit looks magnificent

**Comment by vivekimsit** [comment]
Need to chime in now :)

Why not use closure compiler? Would help in code minification and documentation at the same time.

[Closure Annotations](https://developers.google.com/closure/compiler/docs/js-for-compiler)

**Comment by shshaw** [comment]
@vivekimsit Looks like Closure uses JSDoc tags, so the documentation should be compatible. 

In the past, I've looked at using Closure Compiler for minification, but the command line tool did not seem  quite as useful or easy to use as Uglify. Maybe it was just difficult to install with it's Java requirements or something. Happy to be proven wrong if you have any suggestions!

**Comment by vivekimsit** [comment]
@shshaw let me tell you it does static code analysis as well so, it would catch much of the potential errors during development only. I think you should read a bit about it.

**Comment by fabiospampinato** [comment]
@shshaw if you agree I'd close this in favor of:
- making cash more aligned (as of v2.1.2 it's much more aligned) with jQuery 
- just assuming people are going to use jQuery's docs
- potentially adding types #151

**Comment by fabiospampinato** [comment]
I'm closing this, for the reasons mentioned above.
