### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#120]
Most of Cash's methods currently work on preexisting SVG elements ( `addClass`, `css`, `attr`, at least in Chrome. Haven't tested deeper. ), but Cash does not work for creating SVG elements ( `$('<rect />')` ).

[Demo](http://codepen.io/shshaw/pen/qZgLOb?editors=0010)

This is likely related to our current `parseHTML`. Pull request #105 does not seem to fix it, but we may be able to add some sort of whitelist to use an SVG document fragment (  `doc.implementation.createDocument('http://www.w3.org/2000/svg')` ) instead of the normal document fragment ( `doc.implementation.createHTMLDocument();` ).

Is this something we want to support? Manipulating SVG is something I do frequently, so having cash's easy API available to create SVG would be quite helpful.

**Comment by kenwheeler** [comment]
Absolutely

**Comment by shshaw** [comment]
I've tried implementing this in a few different ways, but I keep running into a strange issue where every other time the SVG elements are not created with the proper namespace. The element is created and works as a normal element, but because it isn't namespaced correctly (either `null` or `http://www.w3.org/1999/xhtml`) it will not display.

Creating an entire SVG in one string is fine, and probably already works with the existing `parseHTML`
```
$('<svg viewBox="0 0 100 50"><circle cx="40" cy="25" r="20" fill="#F00" /><circle cx="50" cy="25" r="20" fill="#0F0" /><circle cx="60" cy="25" r="20" fill="#00F" /></svg>').prependTo(document.body);
```

But creating them individually with Cash causes the every-other issue:
```
var $svg = $('<svg viewBox="0 0 100 50" />').prependTo(document.body); 
var $redCircle = $('<circle cx="40" cy="25" r="20" fill="#F00" />').appendTo($svg); // Works fine!
var $greenCircle = $('<circle cx="50" cy="25" r="20" fill="#0F0" />').appendTo($svg); // Where's my green circle?
var $blueCircle = $('<circle cx="60" cy="25" r="20" fill="#00F" />').appendTo($svg); // This one works.
```

Here are the different methods I've tried, all react the same across Chrome, Firefox & Safari. The issue seems to even persist across different methods. Not sure what's going on here and Google doesn't seem to be turning up anything. Any thoughts? Something I'm missing?

[CodePen Tests](http://codepen.io/shshaw/pen/eZXJMY?editors=0010)

**Comment by shshaw** [comment]
[DOM Parser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) could be the answer, though it's only supported in IE10+, breaking our IE9 compatibility.

**Comment by simeydotme** [comment]
crazy idea here...

could we just store/convert `<svg>` tags as `<div>` fragments, and then after all manipulation is done, convert back to SVG ?

I wonder if these issues are why I can't even run `.addClass()` on `<svg>`in jQuery ?

**Comment by shshaw** [comment]
Latest version of jQuery should support class manipulation for SVG. In
testing on Chrome, Cash works for that. May be issues in IE or something.
Worth further testing to be sure.

The issue I'm having is the SVG elements aren't in the correct namespace so
they don't display when in an SVG element. We might be able to set the
namespace after they're created, but I don't think converting to div would
help, at least in the creation process.

**Comment by shshaw** [comment]
It appears that `namespaceURI` is a read-only property, so it can't be converted after creation, either. Hm.

**Comment by shshaw** [comment]
Ah! The issue was apparently `RegExp.test` incorrectly returning a false-y value, appending the SVG element to the regular document fragment. Instead, using String.match works as expected. [Updated CodePen](http://codepen.io/shshaw/pen/eZXJMY?editors=0010)

Now to run some performance tests on the different methods...

**Comment by fabiospampinato** [comment]
I'm closing this since as of cash v3 we have better SVG support, all the snippets of code posted here that didn't work before work now, like: `$('<rect />')`, `$('<svg viewBox="0 0 100 50" />')` and `$('<circle cx="40" cy="25" r="20" fill="#F00" />')`.
