### ISSUE TITLE
Passing 0 to $.fn.text() 

### ISSUE THREAD

**Issue by e-neko** [kenwheeler/cash#125]
I noticed this behavior when chaining DOM creation commands, jQuery-style.
When passing 0 as argument, the function returns element's text content instead of element itself, thus preventing chaining.
jQuery checks function parameter value === undefined, while cash only checks !value.
This bug will also happen when attempting to pass any _falsy_ value, including empty string.

**Comment by shshaw** [comment]
Good catch. That was an issue with another method as well. I'll see about getting that patched.

**Comment by shshaw** [comment]
Fixed in 1.3.4

Thanks!
