### ISSUE TITLE
Errors with crawlers

### ISSUE THREAD

**Issue by rwwagner90** [kenwheeler/cash#126]
I'm not sure exactly what is happening here, but something with Googlebots accessing our page is throwing errors. I believe it is on this line: https://github.com/kenwheeler/cash/blob/8a90ca6c222c7ab9729e68d15d735e3de1ecda6d/src/manipulation.js#L19

This is our stack trace:
```
error: [TypeError: undefined is not a function] TypeError: undefined is not a function
    at null.<anonymous> (about:/Users/shamirsaddler/Developer/projects/node/jibe-apply-app/node_modules/jibe-search-module/node_modules/jibe-juice/dist/ui.js:7051:17)
    at each (about:/Users/shamirsaddler/Developer/projects/node/jibe-apply-app/node_modules/jibe-search-module/node_modules/jibe-juice/dist/ui.js:6560:21)
    at insertContent (about:/Users/shamirsaddler/Developer/projects/node/jibe-apply-app/node_modules/jibe-search-module/node_modules/jibe-juice/dist/ui.js:7049:6)
    at cash.fn.extend.append
```

It is tough to really make a reproducible test case with our code, but our code is doing something like `$('.foo').append` when this error occurs.

Any ideas what may be happening here? We'd really prefer not to have to go back to jQuery!

**Comment by shshaw** [comment]
Very odd. Is this happening in browser, or is it only happening when Googlebot is crawling the page?

What exactly are you trying to append ( string, elements, collection ), and what are the collections like you're appending to?

**Comment by shshaw** [comment]
It may have to do with [line 20](https://github.com/kenwheeler/cash/blob/8a90ca6c222c7ab9729e68d15d735e3de1ecda6d/src/manipulation.js#L20) and `.cloneNode`, though I'm just spitballing.

**Comment by rwwagner90** [comment]
@shshaw it only happens with the crawler or when we server side render anywhere, so I'm assuming it has something to do with manipulating DOM server side, when there isn't really DOM. I'm guessing jQuery has some checks for this case, and does some virtual DOM magic, but I really don't know much about the subject.

**Comment by shshaw** [comment]
Do see any errors with using `$` before trying `.append`, or does this only seem to trigger with `.append`?

**Comment by shshaw** [comment]
Also: can you check with `prepend`, `before` and `after` to see if you get any different results?

Without being able to reproduce it myself, it's hard to narrow it down to what may be the issue.

**Comment by rwwagner90** [comment]
@shshaw looks like `$` works okay, other than the append. These are the lines in question in our code:

``` 
assert($.isFunction(this.fetch), 'typeahead requires a fetch method');
this.$el.append(containerHTML);
```

The `$.isFunction` call works fine. So it's not that `$` isn't defined or anything.

In this specific case, I'm not sure who decided to use `.append`, but it looks like `.html` yields the same functional Typeahead, so I will try and see if that eliminates the error here.

**Comment by shshaw** [comment]
How about `$('.classSelector')` and `$('<div>HTML String</div>')`?

**Comment by rwwagner90** [comment]
@shshaw the class selection definitely works, it seems to be only the `append` that does not work here. I switched it to `.html` and it's working great.

**Comment by shshaw** [comment]
Odd. If you get a chance to test with `prepend`, `before` and `after`, let me know what the results are.

**Comment by rwwagner90** [comment]
@shshaw looks to have the same issue with `prepend`

**Comment by shshaw** [comment]
Then I would assume it has to do with `insertAdjacentHTML` as you pointed out with [line 19](https://github.com/kenwheeler/cash/blob/8a90ca6c222c7ab9729e68d15d735e3de1ecda6d/src/manipulation.js#L19).

If you can run a test using that on a plain element (not a cash collection) or show me how you're running the tests, that would be helpful!

**Comment by rwwagner90** [comment]
@shshaw I'm just running it in server side JS with node. I'll try `insertAdjacentHTML` directly and see what happens.

On a related note, we have a gross hack to go through and delete events because without it they just keep stacking and we get memory leaks. Would you be able to enlighten me on how to clear out events using cash? We were doing something like this before with jquery:

```
  var jquery;
  var prop;
  for (prop in global.document) {
    if (prop.indexOf('jQuery') === 0) {
      jquery = prop;
      continue;
    }
  }
  
  // prevent memory leak
  global.document[jquery].events = {};
```

**Comment by shshaw** [comment]
Sounds like there may be something odd going on with your code attaching events continually if both jQuery and Cash are having issues... Double check that you aren't adding events on event trigger and/or in some sort of loop.

Perhaps running it in Node may be an issue, since the events may still be registered/tracking even after the element is removed? Not sure.

At any rate, Cash events aren't globally stored; they are attached to the node itself with `addEventListener` and the events themselves are stored on the element via `$.fn.data` using the key `_cashEvents`. The only way to remove them is through `$.fn.off` for each event name, or running `removeEventListener` on the element.

It looks like jQuery does support `$el.off()` to remove all event listeners on a collection, but that's not currently how Cash is set up.

**Comment by rwwagner90** [comment]
@shshaw we're just adding events on the initial render. We do nothing to remove them later though, so each subsequent render adds another, server side at least.

We may have to do the `$.fn.off` route, although, we didn't use any jquery methods to do it, just cleared out this: `global.document[jquery].events = {};`

**Comment by shshaw** [comment]
Forgive me, I'm not quite familiar with how server side rendering works. Shouldn't the page/DOM be built  on the server, then the events registered on the client?

Sounds like this is a garbage collection issue where the server is retaining all of the nodes & associated data for each build because Cash doesn't keep a global list of events. Everything should be removed/garbage collected whenever the node is no longer in use since all the data is attached to the node and event attached with addEventListener.

**Comment by rwwagner90** [comment]
@shshaw yeah this events issue is on us, not a problem with cash, the initial issue with `append` not working should probably still be addressed though right?

**Comment by shshaw** [comment]
Of course. I'm still interested in tracing down the root of the `append` issue. Let me know if you're able to test `insertAdjacentHTML` in Node.

**Comment by rwwagner90** [comment]
@shshaw seems that this is due to us using an extremely ancient version of jsdom. See this issue https://github.com/tmpvar/jsdom/issues/1219

Must be that jquery just never uses `insertAdjacentHTML`, so we never ran into this issue. Closing, as it is jsdom's fault.

Sorry about that!

**Comment by shshaw** [comment]
Thanks for the followup! Glad to hear it's not some deeper issue. :-)
