### ISSUE TITLE
`$.fn.off()` to remove all events

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#127]
Remove all event listeners using `$.fn.off` with no arguments.

https://github.com/kenwheeler/cash/issues/126#issuecomment-224752185

**Comment by rwwagner90** [comment]
@shshaw would this be usable to remove all events from the body? Something like `$('body').off()`?

**Comment by shshaw** [comment]
@rwwagner90 No, not quite. It would only be for removing events for elements in that collection. `$('body').children().off()` or `$('*').off()` would potentially do that, though.

**Comment by rwwagner90** [comment]
Those solutions may work. We just need an easy way to remove all events, so we can go back to using cash 😄

**Comment by shshaw** [comment]
My [branch for improving events](https://github.com/kenwheeler/cash/tree/event-callbacks) now has this capability. `$('el').off()` and `$('*').off()` both work. 

Download from the /dist/ on that branch and give it a try. The event engine itself was rewritten a bit to patch #114 and other issues, so let me know if you encounter any bugs. Eventually namespacing ( #121 ) should make it into this branch as well. Likely for a 1.4.0 release.

**Comment by fabiospampinato** [comment]
I've implemented this in [my fork](https://github.com/fabiospampinato/cash).

**Comment by fabiospampinato** [comment]
Fixed in v2.1.2.
