### ISSUE TITLE
Convenience events for focusin/out etc with poor cross-brower support

### ISSUE THREAD

**Issue by dominicwhittle** [kenwheeler/cash#128]
Are there plans to polyfil any common events?
Theres some inconsistency in current browser input event listeners; eg focusin and focusout vs focus and blur etc

If not, then how about following jQuery's API in which you can spec multiple space-separated event types?

```
$el.on('focusin blur whatevs', 'input', callbackFn)
// ^ works in jQuery, not Cash
```

**Comment by shshaw** [comment]
Event retooling is one of the biggest changes planned for the next version, mainly fixing some delegate support ( #114 ) and allowing for namespaces ( #121 ). Registering multiple events per callback/delegate shouldn't be a problem.

I'm not sure specifically what you mean by polyfilling common events. Are you referring to inconsistencies between browsers about when `focusout` is triggered versus `blur`?

**Comment by dominicwhittle** [comment]
Cool. 

> Are you referring to inconsistencies between browsers about when focusout is triggered versus blur

That's right. I was wondering if there were plans to account for some of the subtle inconsistencies in events that jQuery seamlessly irons out. I do appreciate that the size of Cash should be a major consideration in any feature like this; eg,
```
$(input).on('focusin', onFocus) // Chrome, Safari, IE
$(intput)[0].addEventListener('focus', onFocus, {useCapture: true}) // Firefox

function onFocus (e) { 
  // do stuff on focus 
}
```

**Comment by shshaw** [comment]
Haven't specifically encountered these bugs. Is it only with `focusin`/`focusout` that you're having difficulty?

Seems like jQuery is mainly fixing `focusin`/`focusout` and `blur`:
https://github.com/jquery/jquery/blob/master/src/event/focusin.js

With a few small fixes for `click` and `load` 
https://github.com/jquery/jquery/blob/master/src/event.js#L442-L494

**Comment by dominicwhittle** [comment]
It's not a bug so to speak, just that (as you say) `focusin`/`focusout` which still aren't supported in Firefox AFAIK, so I'm having to resort to vanilla javascript to handle that via `addEventListener`. It's really not a big deal, but given this is a consistency in current browsers it might be worth considering including in Cash.

**Comment by fabiospampinato** [comment]
Closing as this is mostly no longer an issue since Firefox v52 (~13 versions ago).
