### ISSUE TITLE
npm out of date

### ISSUE THREAD

**Issue by dominicwhittle** [kenwheeler/cash#129]
Any chance you could update the npm release to 1.3.4?
I'm still working around the `text('')` falsey bug.

**Comment by shshaw** [comment]
@kenwheeler is the only one with the access to do so, but I believe he's been quite busy lately. I'll check in with him to see if he can.

**Comment by dominicwhittle** [comment]
@shshaw Awesome :)

**Comment by shshaw** [comment]
Cash 1.3.4 is now up on NPM. @kenwheeler is a saint and has given me NPM collaborator status, so now cash should stay up-to-date on NPM when a new release is out.
