### ISSUE TITLE
IE11 error adding class to SVG

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#131]
`<svg>` elements give this error when using `addClass`.

```
"Assignment to read-only properties is not allowed in strict mode"
```

Seems to be related to using `className`, though I'm seeing more results for IE11 failing on `classList`:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/1173756/

**Comment by fabiospampinato** [comment]
This is no longer a problem in 10+, it probably got fixed when I switched to the `classList` API instead of mutating `className` directly.

```javascript
$('<svg></svg>').addClass ( 'foo' ).hasClass ( 'foo' ); // => true
```
