### ISSUE TITLE
.closest() without a match results in "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by powmedia** [kenwheeler/cash#135]
Please see title and example jsfiddle:
https://jsfiddle.net/30cxw27u/

(Note you need to open browser console in jsfiddle to see the error)

**Comment by shshaw** [comment]
It's possible that the Traversal Fixes ( #133 ) have resolved this. If you have the time, please test using the version from that branch. I'll try to test tomorrow to confirm that it's still an issue.

**Comment by vivekimsit** [comment]
I don't think so, the implementations seems buggy since it would keep traversing the ancestor chain if it doesn't find the matching selector. There should be a check if the document root is reached.

**Comment by shshaw** [comment]
You're right. I've pushed a change to the `traversal-fix` branch that solves this by correcting some issues with `$.fn.parent()` / `$.fn.parents()`. 

Feel free to test and let me know if you have any feedback. I'll try to add some basic Qunit tests for all of these fixes so the pull request can be merged as 1.3.5

**Comment by vivekimsit** [comment]
I doubt about the implementation of [parent](https://github.com/kenwheeler/cash/blob/4c3f640b3b90db6ec42717c95347f8a154ededf0/src/traversal.js#L71) method, it should return a single element for collection there is already a parents method.

**Comment by shshaw** [comment]
`$.fn.parent` is modeled after jQuery's parent method, which is described in the documentation as:
> Get the parent of each element in the current set of matched elements, optionally filtered by a selector.

So `$.fn.parent` returns the direct parent for each element in the collection. `$.fn.parents` is to retrieve the ancestors of every element in the collection.
