### ISSUE TITLE
Disabled form element shouldn't be serialized.

### ISSUE THREAD

**Issue by vivekimsit** [kenwheeler/cash#137]
Following the code here:

https://github.com/kenwheeler/cash/blob/master/src/forms.js#L12-L28

There should be check like `element.disabled` before doing any computation.

**Comment by shshaw** [comment]
Good catch. I think a simple `!field.disabled` check on [line 17](https://github.com/kenwheeler/cash/blob/master/src/forms.js#L17) is all that's needed.

**Comment by shshaw** [comment]
Fixed in [1.3.5](https://github.com/kenwheeler/cash/releases/tag/1.3.5)
