### ISSUE TITLE
1.3.5

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#139]
There are a lot of useful bug fixes that are ready to launch, though we could use further testing especially once merged.

Here's what I have on the current list for 1.3.5:

# [Milestone 1.3.5](https://github.com/kenwheeler/cash/milestone/4)

## Pull Requests
~~#105~~, ~~#116~~, ~~#123~~, ~~#124~~, ~~#133~~, ~~#136~~, ~~#138~~, ~~#140~~, ~~#145~~

## Issues fixed
#137 #134 #132 #143 

Any concerns, @simeydotme @kenwheeler? I'll attempt to [merge the pull requests into a 1.3.5 branch](https://github.com/kenwheeler/cash/pull/109#issuecomment-216929826) before release.

**Comment by influxweb** [comment]
Any ETA on the release of 1.3.5? I was testing out 1.3.4 to see if it would work with a small project, but I ran into the traversal bugs listed in #133. When I tried 1.3.5 it made me happy 😀

**Comment by shshaw** [comment]
Just got finished working around the clock on a project for my day job. Today I'm catching up on missed emails and to-dos, but I should have some time this week to put together 1.3.5 for release.

**Comment by shshaw** [comment]
These changes should all be merged in release [1.3.5](https://github.com/kenwheeler/cash/releases/tag/1.3.5)

**Comment by shshaw** [comment]
NPM should be up to date as well https://www.npmjs.com/package/cash-dom
