### ISSUE TITLE
Handlers won't run in IE and Edge when triggering events

### ISSUE THREAD

**Issue by thasmo** [kenwheeler/cash#144]
This doesn't work for me in IE and Edge:
```js
var element.on('click', function() { alert 'yay'; };
element.trigger('click');
```

**Comment by thasmo** [comment]
Seems to only work in Firefox.

**Comment by shshaw** [comment]
Working in Chrome, Safari, Firefox, Edge, IE11, IE10 and IE9 in [my test](http://codepen.io/shshaw/pen/PzagNQ).

Is it possible `element` is an empty collection? Events won't trigger without an element to trigger them on.

**Comment by thasmo** [comment]
Nah, it's not an empty collection - it is/was working in Firefox. I was in a hurry and changed the code to call my functions directly, omitting the use of trigger for now. So at the moment I can't reproduce the bug myself anymore - maybe when I got time I'm gonna create a test-case.

**Comment by shshaw** [comment]
Yes, more info would be nice. What kind of elements were in the collection may be an important factor.

Let me know if you're able to reproduce it again, and I'll reopen this.
