### ISSUE TITLE
`$(window).off('resize');` doesn't seem to work on iOS Safari

### ISSUE THREAD

**Issue by thasmo** [kenwheeler/cash#149]
Doesn't work on iOS Safari.

``` js
$(window).on('resize', function() {
    window.alert('meh');
});

$(window).off('resize');
```

**Comment by shshaw** [comment]
Hm. Working on Desktop Safari 10. Which version of iOS Safari?

And how are you triggering 'resize' on iOS Safari? With device rotation?

**Comment by fabiospampinato** [comment]
No needed info provided, I'm closing this.
