### ISSUE TITLE
ajax implementation is too lightweight

### ISSUE THREAD

**Issue by jods4** [kenwheeler/cash#15]
A few things jQuery does and I really miss:
1. Set the content-type myself: I often post JSON payloads to my server.
2. Return the xhr object (or a wrapper): e.g. to be able to call .cancel() on it.
3. Return a Promise, because programming async code with callbacks is hell when you do more than trivial stuff. This is also the way to go with modern browsers (await is proposed for ES7).

**Comment by simeydotme** [comment]
https://github.com/pyrsmk/qwest
https://github.com/github/fetch

^^ think these are the best AJAX libraries to use :) - they are nice and familiar for jQuery users - perhaps can add them to the CASH page like we did for Velocity :)

**Comment by joezimjs** [comment]
Looks like there is no AJAX implementation (according to README) for 1.0. Should this be closed?

**Comment by shshaw** [comment]
AJAX is no longer a part of cash, as of version 1.0.0. As @simeydotme suggested, try using an AJAX specific library like fetch for jQuery-less AJAX support.
