### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by eugenioclrc** [kenwheeler/cash#151]
Just saying, i would be grate to have typings for cash-dom, i couldn find any in the wild.

**Comment by RenaudParis** [comment]
Agreed!

**Comment by Micene09** [comment]
Using this library at work, typings really need here!

**Comment by ChristianLJ** [comment]
Same here!

**Comment by fabiospampinato** [comment]
Currently our bundler doesn't support typescript compilation.

I'll keep an eye on the popularity of the request, and if it's high, and if there's somebody who volunteers for doing the necessary work I'll add typescript support to our bundler.

**Comment by fabiospampinato** [comment]
They aren't accurate at all, the projects changed quite dramatically in the past few months.

**Comment by CiriousJoker** [comment]
Well, I have to say that I resorted to using jQuery for the time being while remembering not to use any jQuery-only functionality :(

**Comment by fabiospampinato** [comment]
@CiriousJoker feel free to open other issues about missing features, maybe there are worth implementing.

**Comment by fabiospampinato** [comment]
I've kind of rewritten `cash` in TypeScript 🎉 

It isn't quite ready for being published as v2.4 yet, as there a few things I'd like to do first:

- Fix all type errors
- Test it thoroughly -- even though our test suite is already passing it could/should be improved
- Check if functions are typed correctly
- Maybe add TSDoc-style comments

You can get it [here](https://github.com/kenwheeler/cash/tree/master/dist), I'll be glad if you could try it out and report any issues you may find.

I'd like to highlight that contrary to the other major DOM manipulation libraries (jQuery, Zepto...) our types are actually generated from the code, and not hand-written by somebody. This is especially important for partial builds: if you build your custom version of `cash` you'll get proper types too.

**Comment by fabiospampinato** [comment]
You can try the new version (v3) by doing `npm i cash-dom@next`, let me know if you find any issues with it 👍 It is currently released as beta, I'd like to try it first in production before releasing it as `@latest`.
