### ISSUE TITLE
Selecting Form Elements

### ISSUE THREAD

**Issue by influxweb** [kenwheeler/cash#152]
I am working on a small form project and though cash would be a nice script to use. One issue I have run into is trying to use `$('form').find(':input')` as a `var` for an `each()` function. When I try, I receive the error, "Failed to execute 'querySelectorAll' on 'Element': ':input' is not a valid selector". Is there any way to implement the ':input' selector into cash?

**Comment by dominicwhittle** [comment]
The equiv would be `const inputs = $('form').find('input, select, textarea, button')`

I can't speak for the cash maintainers, but the jQuery ':input' selector isn't especially performant according to the [docs](https://api.jquery.com/input-selector/) so I'm not sure how valuable adding it to cash would be.

**Comment by influxweb** [comment]
Thanks for the clarification @dominicwhittle , I totally blanked on the performance side of the equation.

**Comment by shshaw** [comment]
Yes, custom psuedo selectors have been avoided thus far for performance & size reasons. These selectors would also add a lot of complexity to the logic, pulling the project away from trying to be a simpler alternative for jQuery.
