### ISSUE TITLE
Native Events not triggered

### ISSUE THREAD

**Issue by martinheidegger** [kenwheeler/cash#154]
Trying to `.trigger('click')` on a `<input type="file">` does nothing because `node.click()` is not called.

**Comment by shshaw** [comment]
Hm, that's a good catch. `click` and others (`mousedown`, `change`, `blur`, `focus`, etc) should trigger the native event.

From the information I can find, a lookup table has to be used to create the proper type ( `HTMLEvent` or `MouseEvent` ).

Rough code without a lookup: http://codepen.io/shshaw/pen/JRvkwK?editors=1010

Here's how a few others have handled it: 
https://github.com/adamsanderson/trigger-event/blob/master/index.js
https://gist.github.com/balupton/796871

**Comment by fabiospampinato** [comment]
Fixing this seems quite expensive bytes-wise.

For the time being I recommend replacing this:

```js
$('input[type="file"]').trigger ( 'click' )
``` 

with something like this:

```js
const $input = $('input[type="file"]');
if ( $input.length ) {
  $input[0].click ();
}
```

**Comment by fabiospampinato** [comment]
> Hm, that's a good catch. click and others (mousedown, change, blur, focus, etc) should trigger the native event.

`focus` and `blur` are now called natively. I'll see what should be done for the remaining ones.

**Comment by fabiospampinato** [comment]
We are now triggering `MouseEvents` when appropriate. As a result the following now works as expected:

```javascript
$('input[type="file"]').trigger ( 'click' )
```
