### ISSUE TITLE
parseHTML implementation broken in IE 11 and Edge

### ISSUE THREAD

**Issue by AugustMiller** [kenwheeler/cash#156]
Looks like the following code blows up in IE 11 and Edge:

```js
function parseHTML(str) {
  if (!frag) {
    // This cannot be called in the above IE versions “without an argument”:
    frag = doc.implementation.createHTMLDocument();
    var base = frag.createElement("base");
    base.href = doc.location.href;
    frag.head.appendChild(base);
  }

  frag.body.innerHTML = str;

  return frag.body.childNodes;
}
```

Changing the offending line to:

```js
frag = doc.implementation.createHTMLDocument(null);
```

…seems to make IE happy. This is an astonishing error from Microsoft— I couldn't find much good information on it, and `createHTMLDocument` has been part of IE's API since version 9.

I'll issue a PR in a moment.

**Comment by shshaw** [comment]
Yikes. Thanks for tracking that down. 

I don't think adding `null` will hurt any other browsers, but if you could run some quick tests to ensure Chrome, Firefox and Safari aren't thrown off by this, then I'll get this fix pulled in and patched.

**Comment by AugustMiller** [comment]
Well 👋 there! Issued PR #157, but I'll update when I've had a moment to look at some other browsers.

**Comment by AugustMiller** [comment]
I chose to pass `null`, but [the spec](https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument-title-title) asks for a “`DomString`”. Seems like you _can_ pass `''` for the same effect, but that would actually change the type of what's been passed to other browsers that don't seem to care…

Discussion of [a similar issue](https://bugs.webkit.org/show_bug.cgi?id=96694) in Webkit (2012) indicates that `null`, `undefined` and `''` should all be acceptable input.

**Comment by AugustMiller** [comment]
Tested in Chrome 54, Firefox 49, Safari 10, IE 11, Edge 13+14. Seems to be working 👌.

**Comment by shshaw** [comment]
Thanks, @AugustMiller. I'll take a look over it this week and pull it after a quick test.

**Comment by softwarespot** [comment]
With jQuery's implementation, they pass an empty string
Source: https://github.com/jquery/jquery/blob/master/src/core/parseHTML.js#L33

**Comment by dominicwhittle** [comment]
This is broken again in edge in cash 1.3.5

1.3.5 — https://codepen.io/dominicwhittle/pen/wexGLe 😞
1.3.0 — https://codepen.io/dominicwhittle/pen/KqBzbZ 👌

**Comment by DanielRuf** [comment]
Still not merged and released as new release.
