### ISSUE TITLE
$(window).width() causes getBoundingClientRect error

### ISSUE THREAD

**Issue by lsbyerley** [kenwheeler/cash#162]
Using $(window).width() causes this error

> this[0].getBoundingClientRect is not a function

at this line https://github.com/kenwheeler/cash/blob/0ff26e3e6694f36d22af042eeb43423378761191/dist/cash.js#L492

How i'm using it..
~~~~
window.cash = require('cash-dom');

(function(window, document, $) {
	'use strict';

	$(document).ready(function() {
		console.log( $(window).width() );
	});
	
})(window, document, window.cash);
~~~~

Has anyone else run into this issue, or a possible solution?

**Comment by fabiospampinato** [comment]
`window.getBoundingClientRect` doesn't exist, so you shouldn't do this. Just use `window.innerWidth` instead.

**Comment by fabiospampinato** [comment]
As of v2.3.1 you can now do `$(window).width ()`, all the others dimensions-related methods are supported as well.
