### ISSUE TITLE
Dimensions Enhancement Request

### ISSUE THREAD

**Issue by influxweb** [kenwheeler/cash#163]
While working on a project, I came across the need for calling a function within an outerWidth call. However, it looks like Cash does not support this. Is it possible to get the function ability added like it is in jQuery [[outerWidth: function]](http://api.jquery.com/outerWidth/#outerWidth-function) ?

Thank you,
Matt

**Comment by fabiospampinato** [comment]
There are many places where jQuery accepts a function instead of a scalar value, if we add support for your particular use case I think we should also support all other use cases. 

I personally think it's more important to keep the codebase tiny than to support features like this.

**Comment by influxweb** [comment]
Thank you for the feedback @fabiospampinato . I could not agree with you more. I am sure I figured something back then...I just cannot remember what it was. I should have closed this issue long before this.
