### ISSUE TITLE
Data attributes with hypens invalid?

### ISSUE THREAD

**Issue by howells** [kenwheeler/cash#170]
Am I being incredibly dumb here, or are data attributes that have hyphens in them not recognised by cash dom's `.data()`?

For example, `data-react-props` would be read as expected in jquery, but in cash dom, `.data('react-props')` results in an undefined value. Changing the attribute to `data-reactprops` and using `.data('reactprops')` works as expected.

**Comment by fabiospampinato** [comment]
I've just tried this, and it's working as expected for me.

**Comment by fabiospampinato** [comment]
Fixed in v2.1.2.
