### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by DanielRuf** [kenwheeler/cash#172]
@shshaw please make a new release. 1.3.5 has some bugs for example in IE11.

**Comment by shshaw** [comment]
https://github.com/kenwheeler/cash/releases/tag/1.3.6

**Comment by shshaw** [comment]
I've published to NPM as well. https://www.npmjs.com/package/cash-dom

Let me know if you run into any issues with the merged requests. Tests passed, but I haven't been able to do deep browser testing.

**Comment by DanielRuf** [comment]
Great, thanks for investing the time to maintain Cash.

**Comment by shshaw** [comment]
Appreciate that. Sorry for delays; Cash just hasn't been a big priority on my list anymore because I've been moving more towards frameworks and vanilla JS in my daily development.
