### ISSUE TITLE
NPM Packaging gone wrong

### ISSUE THREAD

**Issue by acydburn** [kenwheeler/cash#174]
Hi,

the release 1.3.6 is fine, but within the npm package there are 0-byte Files with the name "Icon" in each directory. This file results in the following error (with yarn --no-bin-links):

```
Trace: 
  Error: EPROTO: protocol error, copyfile '[...]/.cache/yarn/v1/npm-cash-dom-1.3.6-ab344d8aa6ce1ff080904886ba9452e96a1d26ea/dist/Icon
' -> '[...]/node_modules/cash-dom/dist/Icon
'
```

To verify: Download @ https://registry.npmjs.org/cash-dom/-/cash-dom-1.3.6.tgz or look in your cache dir.

At the moment we use 1.3.5 instead of manually removing the Icon files from the cache,

**Comment by shshaw** [comment]
Apologies, that's from a syncing tool. They're ignored in git, but NPM must still push them.

Just pushed 1.3.7 to NPM. I'm not seeing those files in the package anymore, but please verify.

**Comment by acydburn** [comment]
No problem - works now. :)

Thanks for fixing this so fast.

Best, 
Meik
