### ISSUE TITLE
Support with 3rd-party libraries

### ISSUE THREAD

**Issue by ChristianLJ** [kenwheeler/cash#179]
Hi there!

I am looking for a smaller alternative to jQuery and this seems to fit my needs mainly because of its small size and support for IE9+. (We're running a webshop).

I am using the following jQuery-dependent libraries. Can someone tell me if cash will work together with other jQuery libraries like the following?

```json
  "dependencies": { 
    "jquery-bar-rating": "^1.2.2",
    "jquery-validation": "^1.17.0",
    "lightslider": "^1.1.6",
    "typeahead.js": "^0.11.1",
    "sidr": "2.2.1",
    "simple-pagination.js": "^1.6.0",
    "sweetalert2": "^7.13.1"
}
```

Thank you.

**Comment by fabiospampinato** [comment]
As of v2.1.2 cash is much more aligned with jQuery. If those plugins don't rely on things cash doesn't implement they should work fine.

I'm closing this as we can't really test stuff for you, although if you'll test this on your own, and find problems with cash, feel free to open new issues about it :)
