### ISSUE TITLE
Add wrap() and wrapAll()

### ISSUE THREAD

**Issue by kenwheeler** [kenwheeler/cash#18]
and wrapAll()

**Comment by kenwheeler** [comment]
I aim to make it as jQuery compatible as possible, however the way I see Cash, the focus is on the DOM utilities for the most part. In todays modern workflow, there are better modules for things like animation or promises or ajax that would just bloat Cash and there is no sense in trying to replicate.

**Comment by fabiospampinato** [comment]
If somebody wants to submit a PR for this I'll be happy to consider it.

**Comment by influxweb** [comment]
I had need for a wrapping function in a carousel I was creating. The goal was to use Cash and 'vanilla' JavaScript while allowing for a developer to swap out Cash for jQuery if they needed to for other functionality.

Here is the wrapping function I used in case it could be helpful to others.
```javascript
$.fn.wrapElements = function (html) {
	if (jQuery.isFunction(html)) {
		return this.each(function (i) {
			jQuery(this).wrapElements(html.call(this, i));
		});
	}

	if (this[0]) {
		// The elements to wrap the target around
		var wrap = jQuery(html, this[0].ownerDocument).eq(0).clone(true);

		if (this[0].parentNode) {
			wrap.insertBefore(this[0]);
		}

		wrap.map(function () {
			var elem = this;

			while (elem.firstChild && elem.firstChild.nodeType === 1) {
				elem = elem.firstChild;
			}

			return elem;
		});
		wrap.append(this);
	}

	return this;
};

$.fn.groupEvery = function (cLen, wrapperEl, wrapperClass) {
	var wrapper = document.createElement(wrapperEl);

	wrapper.classList.add(wrapperClass);
	while (this.length) {
		$(this.splice(0, cLen)).wrapElements(wrapper);
	}
};


/**
 * groupCount = number of elements to wrap, i.e 3
 * groupWrapper = element to wrap the group(s) in, i.e. 'figure'
 * groupClass = class to apply to wrapping element, i.e. 'x-carousel__item'
 */

$('#ELEMENT').groupEvery(groupCount, groupWrapper, groupClass);
```

**Comment by MaikelGG** [comment]
@influxweb Do you know why adding multiple classes as an argument throws an error? When I look at the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList), classlist should work with comma separated classnames.

```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('classone classtwo') contains HTML space characters, which are not valid in tokens.
```

**Comment by influxweb** [comment]
@MaikelGG I haven't tried passing multiple classes through the `groupClass` variable. You might try something like `var groupClass = '"foo", "bar", "baz"';`.

**Comment by MaikelGG** [comment]
@influxweb just wanted to share the solution:

Changed your function slightly and use the spread operator.
wrapper.classList.add(...wrapperClass);

The groupClass always needs to be an array, but this array can also contain one item.
```
let groupClass = ['datatables-header__colvis', 'datatables-toolbar__item'];
$('.buttons-colvis').groupEvery(1, 'div', groupClass);
```

**Comment by influxweb** [comment]
@MaikelGG I like that idea. Could you post your updated function? I'd like to play around with it and see about making it work still in IE11.

**Comment by MaikelGG** [comment]
Good notice. I have not tested that yet. Will do today. I think (of what I read) you need to use the [babel polyfill](https://babeljs.io/docs/en/caveats/). 

```
/**
 * groupCount = number of elements to wrap, i.e 3
 * groupWrapper = element to wrap the group(s) in, i.e. 'figure'
 * groupClass = class to apply to wrapping element, i.e. 'x-carousel__item'
 *
 * How to use:
 * $('#ELEMENT').groupEvery(groupCount, groupWrapper, groupClass);
 * 
 */

$.fn.wrapElements = function (html) {
	if (jQuery.isFunction(html)) {
		return this.each(function (i) {
			jQuery(this).wrapElements(html.call(this, i));
		});
	}

	if (this[0]) {
		// The elements to wrap the target around
		var wrap = jQuery(html, this[0].ownerDocument).eq(0).clone(true);

		if (this[0].parentNode) {
			wrap.insertBefore(this[0]);
		}

		wrap.map(function () {
			var elem = this;

			while (elem.firstChild && elem.firstChild.nodeType === 1) {
				elem = elem.firstChild;
			}

			return elem;
		});
		wrap.append(this);
	}

	return this;
};

$.fn.groupEvery = function (cLen, wrapperEl, wrapperClass) {
	var wrapper = document.createElement(wrapperEl);

	wrapper.classList.add(...wrapperClass);
	while (this.length) {
		$(this.splice(0, cLen)).wrapElements(wrapper);
	}
};

```
