### ISSUE TITLE
Looking for a maintainer?

### ISSUE THREAD

**Issue by fabiospampinato** [kenwheeler/cash#180]
@kenwheeler @shshaw @simeydotme @jamiebuilds 

This project is practically abandoned, and I've recently [forked](https://github.com/fabiospampinato/cash) it.

My fork includes some new features, including custom builds, and fixes many of the issues present in this repo and others that I've found reading the code. Related issues:

- https://github.com/kenwheeler/cash/issues/92
- https://github.com/kenwheeler/cash/issues/93
- https://github.com/kenwheeler/cash/issues/94
- https://github.com/kenwheeler/cash/issues/107
- https://github.com/kenwheeler/cash/issues/113
- https://github.com/kenwheeler/cash/issues/114
- https://github.com/kenwheeler/cash/issues/121
- https://github.com/kenwheeler/cash/issues/127
- https://github.com/kenwheeler/cash/issues/130
- https://github.com/kenwheeler/cash/issues/165
- https://github.com/kenwheeler/cash/issues/167
- https://github.com/kenwheeler/cash/issues/170
- https://github.com/kenwheeler/cash/issues/181

I'm going to use cash in my [ui framework](https://github.com/svelto/svelto), which I've been actively developing and using for the past 4+ years, so I'm going to maintain my fork of cash for the foreseeable future too.

If you guys want me to, I can become a maintainer and keep this repo alive.

What do you think?

**Comment by adamspruijt** [comment]
I obviously have no real say on this, but I'd love to see some progress in the discussion. I like using Cash in my projects but of course worry when support seems to have died.

**Comment by Epskampie** [comment]
I'm very interested in a small jquery alternative for use with React, and would much prefer that this one stays maintained, as it seems very nice and is easily found with google. Improving one package is always better than starting yet another alternative.

@kenwheeler Please consider adding some maintainers (preferably more then one for robustness). @fabiospampinato  seems like a nice first candidate.

**Comment by fabiospampinato** [comment]
### Updates

- I'm going to wait for a decision until the **7th of June** (2 full months after I opened this issue), if there's still no news I'm just going to rename my fork to something else and move on, I want to be able to accept issues in my repo and possibly gain some users.

### Clarifications

- My fork aims to implement a **subset** of jQuery, which this repo currently does not (errors on empty collections, $.fn.width/height work differently, event delegation is broken, $.fn.remove not removing events and many more things), basically every implemented individual feature should work the same as jQuery.
- My fork is generally more open to adding some new missing methods, since it supports partial builds.
- It's cool if there'll be multiple maintainers, but for me to be one of them our design goals must be aligned, I don't want to pivot my fork into something fundamentally different basically (removing methods, removing partial builds etc.).

**Comment by shshaw** [comment]
Apologies for the delay, @fabiospampinato. Thank you for the time you've put into this so far.

I don't have access to give you maintainer rights, but I'll reach out to @kenwheeler. I don't think that either of us have the time or drive to continue maintaining cash as we have both moved away from jQuery-like DOM manipulation in our main projects, but cash doesn't necessarily need to die.

Keep in mind the main goal with cash is to be a super lightweight alternative to jQuery. Feature parity is not essential except where adding a feature (or set of features) will not add considerable bulk. One feature may only add 0.5kb or so, but when you start implementing a ton of features that _all_ add 0.5kb then... you end up with jQuery sizes before you know it.

The partial build support is interesting, especially if that supports tree-shaking within build systems. However there should still be strong consideration of each feature added as I'm sure most people are not doing custom/partial builds of cash and are instead just including the whole library.

**Comment by fabiospampinato** [comment]
@shshaw thanks for your message.

> Keep in mind the main goal with cash is to be a super lightweight alternative to jQuery. Feature parity is not essential except where adding a feature (or set of features) will not add considerable bulk.

Feature parity isn't a goal of my fork either, for instance jQuery's `$.fn.css` method supports being called like so `css ( property, function )`, which is not something I plan on supporting. 

On the other hand I think every feature we say we support should mostly be a drop-in replacement for jQuery's version of that feature. Just to name a few examples where in this repo currently this isn't the case:
- cash's `$.fn.removeData` may actually remove the data attribute, jQuery's just removes the retrieved value from its internal cache.
- cash's `$().width ()` throws an error while jQuery's returns `undefined`.
- cash's  `$.fn.each|map|filter` don't pass arguments in the same order as jQuery's.

I think it's important that cash implements a subset of jQuery, if it starts behaving weirdly (or at least in a way that jQuery doesn't) how can people replace jQuery with cash or even use cash from the start. All this not-so-little differences in behavior often aren't even documented anywhere, I think people simply assume cash's methods work like jQuery's.

There are some exceptions to this though, for instance with jQuery one can write `$(':hidden')` or `$foo.find ( '> .bar' )`, I'm not going to import [Sizzle](https://sizzlejs.com/) or something just to support this.

> The partial build support is interesting, especially if that supports tree-shaking within build systems. 

Unfortunately it doesn't support tree shaking, a configuration must be written manually instead. For instance [this](https://github.com/fabiospampinato/cash/blob/master/resources/pacco/qsa.json) is what a configuration for having only the query selector (`$()`) available would look like, the returned bundled is 0.7kb minified and gzipped.

> However there should still be strong consideration of each feature added as I'm sure most people are not doing custom/partial builds of cash and are instead just including the whole library.

I think one way of addressing the problem could be to implement "large" useful methods, but to disable them in the default build. That being said at the moment there aren't any new methods I'd like to include.

At the moment the current version of cash, minified and gzipped weighs 3758 bytes, mine weights 4391 bytes, I think that's acceptable for all the improvements I made, if it isn't I can try to use fewer bytes or/and disable by default the `replaceWith` and `replaceAll` methods or something.

**Comment by kenwheeler** [comment]
Added as a collab, you're all set

**Comment by fabiospampinato** [comment]
Awesome, thanks!

I'll merge back my commits and close any resolved issues in this repo as soon as I can.

**Comment by shshaw** [comment]
@fabiospampinato I've added you on NPM as well so you can bump the version there.

**Comment by fabiospampinato** [comment]
@shshaw thank you, I'll push an update there, and update the readme shortly.
