### ISSUE TITLE
$.fn.on with a delegate provided: $(this) returns parent, not delegate

### ISSUE THREAD

**Issue by adamspruijt** [kenwheeler/cash#188]
Example:

```
<div class="calendar">
    <div class="next"></div>
</div>
```

```
$(".calendar").on('click',".next",function(){
	console.log($(this));
});
```

$(this) returns 
`{0: div.calendar, length: 1} `
instead of 
`{0: div.next, length: 1}`

I don't believe this is correct behavior.

**Comment by fabiospampinato** [comment]
Thanks for reporting the issue, I've fixed it in v2.1.6 (https://github.com/kenwheeler/cash/commit/8ad05a5a9d83caa20c41eff09a02e4546eefe6fa).
