### ISSUE TITLE
noConflict

### ISSUE THREAD

**Issue by dimvic** [kenwheeler/cash#190]
It would be nice if [noConflict](https://api.jquery.com/jquery.noconflict/) was available.
I understand it is very easy to save the value of `$` in a temp var before and restore it manually after loading Cash, but when combining and minifying a few files this is not very comfortable.

**Comment by fabiospampinato** [comment]
@dimvic for what practical use case do you need this exactly?

**Comment by dimvic** [comment]
I want to replace jQuery with Cash on an old project that I maintain which uses prototype + jQuery with noConflict, because all that it really uses from jQuery is collections and events.
I will do it by adding the extra scripts before and after loading Cash, it would just be easier if noConflict was there.

**Comment by fabiospampinato** [comment]
I'll leave this open and keep an eye on the popularity of the request, but to me the uses cases for it are just too narrow, and we're trying to keep cash usable but very small, I'd prefer not to add not-so-useful stuff to it.

**Comment by fabiospampinato** [comment]
Closing this as `$.noConflict` is not useful enough to be included in `cash`.
