### ISSUE TITLE
Plugins and jQuery compatibility?

### ISSUE THREAD

**Issue by pwFoo** [kenwheeler/cash#191]
Because In use just some features and plugins of jQuery. 
Are cash plugins available or (some) jQuery plugins compatible to cash?

**Comment by fabiospampinato** [comment]
Every jQuery plugin that doesn't use anything that's not implemented by cash should work, if it doesn't please open up an issue about that.

I'm trying to keep the project as close as jQuery in terms of behavior, but every once in a while I discover a way in which the two APIs behave differently and I fix that, so there might still be some (hopefully minor) incompatibilities.
