### ISSUE TITLE
💰cash logo suggestion

### ISSUE THREAD

**Issue by hisk** [kenwheeler/cash#194]
Hi everyone! 👋

A couple of days ago I published a small roundup of some of the [best resources](https://designrevision.com/resources-for-web-developers-and-designers-may-2018/) for the past month for web developers and also [included](https://designrevision.com/resources-for-web-developers-and-designers-may-2018#cash-js) `$cash` in the list.  I noticed that it had no logo yet so I spent a few minutes trying to create one and I was wondering what do you think about it?

Based on the feedback and ideas I'll get, I can iterate and come up with something more polished if necessary. Let me know your thoughts.

🍻Cheers!

![rfwdd_cash](https://user-images.githubusercontent.com/1017536/41583143-466b437e-73ac-11e8-9b75-fb047fa19335.jpg)

**Comment by fabiospampinato** [comment]
Hey @hisk, thanks for opening this issue!

I personally like the logo you came up with, the use of the bag-of-cash emoji (💰) in particular is such a perfect fit.

I would personally only make these changes:
- Use single quotation marks (') instead of backticks (`) 
- Make the logo less tall (but not the actual text, just the background) so that it doesn't take too much space in the readme
- **Maybe** use a plain white background, I'm not sure if it would look better on the readme or not

Let's wait a couple of days to see if anybody else has got any other ideas. 

Thanks a lot for putting the time into this, I really appreciate it.

**Comment by vivekimsit** [comment]
I am not sure if `cash` is a good name to move forward.

I would be better if we can think of something which describes the library
in the shortest way possible.

**Comment by fabiospampinato** [comment]
@vivekimsit we are not going to rename the library, the cons greatly outweigh the pros. 

I also personally like `cash` as a name, it's short and it makes you think of the dollar sign ($) , which is kind of a synonym of jQuery for many people.

For instance it's a better name than "Zepto", which is just a unit prefix that basically means "very small" (btw cash is smaller) IMO.

**Comment by fabiospampinato** [comment]
@hisk feel free to submit a PR or just post here the updated logo whenever you have the time to. Thanks again!

**Comment by hisk** [comment]
@spruijtdesign I haven't found a clear-cut answer regarding Apple's emoji licensing and most of the clues out there point to contacting Apple's legal department. However, I've seen multiple cases where people have used emoji for branding purposes including in large OS libraries (ie. [styled-components](https://github.com/styled-components/styled-components)).

@fabiospampinato please let me know your thoughts on this and I'll update the logo with a custom illustration if necessary.

**Comment by fabiospampinato** [comment]
I don't think this is a problem, unless @kenwheeler thinks otherwise I'm ok with using Apple's emojis.

**Comment by fabiospampinato** [comment]
Closing this in favor of the PR https://github.com/kenwheeler/cash/pull/195.

**Comment by fabiospampinato** [comment]
@hisk I've just added a "Thanks" section to the readme, which includes a link to your profile thanking you for the logo. Thanks again!

**Comment by hisk** [comment]
@fabiospampinato Thank you Fabio! 🙇
