### ISSUE TITLE
jQuery drop-in?

### ISSUE THREAD

**Issue by eddr** [kenwheeler/cash#197]
Hi and thanks!

Is it supposed to be a jQuery drop-in replacement? if so, what would I do to enable the "$" thing for a project that already built with jQuery?

Thanks

**Comment by fabiospampinato** [comment]
Cash doesn't implement everything that jQuery does, but if you only use things implemented also in cash it should be a drop-in replacement.

> if so, what would I do to enable the "$" thing for a project that already built with jQuery?

Just load cash instead of jQuery.
