### ISSUE TITLE
contains

### ISSUE THREAD

**Issue by alekseymvt** [kenwheeler/cash#199]
Please add a method

> The Node.contains() method returns a Boolean value indicating whether a node is a descendant of a given node, i.e. the node itself, one of its direct children (childNodes), one of the children's direct children, and so on.

https://developer.mozilla.org/en-US/docs/Web/API/Node/contains

**Comment by fabiospampinato** [comment]
I'm not sure this is a worthy addition, right now you can just do `$('#foo')[0].contains ( $('#bar')[0] )` which is not too bad, I think 🤔 

Let's see if some more people want this too.

**Comment by alekseymvt** [comment]
Ok. I agree. I can suggest a version to do this for $.find
`if ($el.find(HtmlElement) .length)`
I think that this would be a suitable solution.
