### ISSUE TITLE
How to build smaller part builds? Build tool available?

### ISSUE THREAD

**Issue by pwFoo** [kenwheeler/cash#200]
Is there a tool or howto about build smaller cash? I don't know pacco. Or is there a web interface to enable / disable parts and methods and generate a custom build?

**Comment by fabiospampinato** [comment]
@pwFoo [here](https://github.com/kenwheeler/cash/blob/master/docs/partial_builds.md) there's some more info, basically you'll have to:

1. Install pacco: `npm i -g pacco`
2. Update the content of `pacco.json`, excluding some files or folders, as done [here](https://github.com/kenwheeler/cash/blob/master/resources/pacco/collection_manipulation_traversal.json)
3. Run `npm run build:deploy`

Unfortunately I still have to properly document pacco.
