### ISSUE TITLE
Add hide() and show()

### ISSUE THREAD

**Issue by CiriousJoker** [kenwheeler/cash#207]
Would save a lot of time.

**Comment by influxweb** [comment]
Looks like that was discussed here #175

**Comment by fabiospampinato** [comment]
@CiriousJoker feel free to submit a PR for this. The fewer bytes it adds the better.

**Comment by fabiospampinato** [comment]
Just implemented.

It adds a few more bytes than what I'm comfortable with, and `hide/show/toggle` aren't really that useful, but those seems to be some methods that people use. Maybe before releasing v3 I'll disable the whole module by default, I'll have to think about this.
