### ISSUE TITLE
2 tests are failing in different platforms

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#211]
Build: https://travis-ci.org/kenwheeler/cash/builds/440702988

![image](https://user-images.githubusercontent.com/6059356/46880731-2187fb00-ce52-11e8-9a2b-da975bfe3bc7.png)

**Comment by fabiospampinato** [comment]
I'll link into that 👍

**Comment by fabiospampinato** [comment]
@limonte can you share the skeleton of your configuration for running those tests locally? I'm always getting a pretty vague error, running `sc` directly shows the following error `Error in detectProxy: Get http://127.0.0.1:2000/proxy.pac: dial tcp 127.0.0.1:2000: connect: connection refused` and I couldn't find anything about it, do I have to open up port 2000 or something?

**Comment by limonte** [comment]
@fabiospampinato there shouldn't be any additional configurations. All you need is

```sh
export SAUCE_USERNAME='...'
export SAUCE_ACCESS_KEY='...'
karma start --single-run --sauce
```

>running `sc` directly

sorry, what is `sc`?

**Comment by fabiospampinato** [comment]
@limonte that's what I did, but it's not working for me 🤷‍♂️ `sc` stands for `sauce connect`, is the thing used for connecting to the server I think, somebody on the internet said to run it directly to see the actual cause of the error.

**Comment by limonte** [comment]
>  it's not working for me

Can you be more specific? Any output or just it just silently fails?

**Comment by limonte** [comment]
You can restart the Travis build. If it'll pass - the issue is on your side (firewall). Which OS are you using?

**Comment by fabiospampinato** [comment]
I guess there's something somewhere in my network stack (I'm not doing anything strange network-wise though) that SL isn't liking. I'm on macOS High Sierra.

Until I get this to work I can't properly work on a fix, running the test manually on IE 10 and Edge worked the last time I tried, I'll try that again just to be sure, if they still pass I guess it's something like the previous failure of the `offsetParent` test.

**Comment by limonte** [comment]
> Until I get this to work I can't properly work on a fix

The development process (including bug fixes) should not happen on remote devices. It'll be much faster to fix them by using local VMs/emulators. SauceLabs is here to indicate issues, it's not to debug them.

I guess you don't need help with Windows VMs. 
Here's my gist how to set up the Android 4.4 emulator: https://gist.github.com/limonte/a6d00f09edccfd66b6a02fd58551b796

**Comment by fabiospampinato** [comment]
> The development process (including bug fixes) should not happen on remote devices. It'll be much faster to fix them by using local VMs/emulators. SauceLabs is here to indicate issues, it's not to debug them.

Sure but I need to reproduce the issue in the first place, and it doesn't reproduce under my VM (Win 10 + IE 10), maybe it has something to do about Win 7, maybe the IE 10 emulation done by IE 11 isn't exactly the same thing as running IE 10.

**Comment by limonte** [comment]
> Sure but I need to reproduce the issue in the first place, and it doesn't reproduce under my VM (Win 10 + IE 10), maybe it has something to do about Win 7, maybe the IE 10 emulation done by IE 11 isn't exactly the same thing as running IE 10.

The same test is failing in Edge 15 and Edge 17 on Win 10.

**Comment by fabiospampinato** [comment]
I couldn't reproduce it on the version of Edge Win 10 comes with. 

I'll probably end up setting up a win7 VM or whatever and test it on the "real" IE10, but this'll probably have to wait a few days.

**Comment by fabiospampinato** [comment]
All tests are passing now, and CI is working properly, is SauceLabs doesn't have any hiccups.

**Comment by limonte** [comment]
Fantastic job @fabiospampinato!

You might want to add the SauceLabs matrix badge to readme to demonstrate that all supported platforms/browsers are covered by automated tests:

https://github.com/vaadin/vaadin-router#browser-support

**Comment by fabiospampinato** [comment]
> You might want to add the SauceLabs matrix badge to readme to demonstrate that all supported platforms/browsers are covered by automated tests:

Thanks for the suggestion, I'll consider it but I'm not a big fan of those things.
