### ISSUE TITLE
Consider providing templates for bug reports and feature requests

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#212]
It would be great to provide templates for bug reports and feature requests for cash users.

This is how SweetAlert2's 'new issue' page looks like:

![image](https://user-images.githubusercontent.com/6059356/46913037-3cf82080-cf8e-11e8-8244-d9fdb0a54ba5.png)

In order to get that handy UI all you need is the ISSUE_TEMPLATE folder: https://github.com/sweetalert2/sweetalert2/tree/master/.github/ISSUE_TEMPLATE

**Comment by fabiospampinato** [comment]
Done, thanks for the suggestion.

**Comment by limonte** [comment]
Lovely!
