### ISSUE TITLE
Travis CI: UnhandledPromiseRejectionWarning: Error: Cannot find module './forAll'

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#216]
This has happened for last 2 builds:

- https://travis-ci.org/kenwheeler/cash/builds/441288243
- https://travis-ci.org/kenwheeler/cash/builds/441285080

This is happening during `npm ci`.

I suspect it's the `npm` issue. My recommendation for _personal_ usage is: use `yarn`, `npm` is a piece of unstable crap, see how they're doing development: https://github.com/npm/cli/pull/2

- 1 developer
- 1 PR
- 377 changed files
- 26,824 changed LoC
- no code review
- no discussion

But, of course, we can't ask all contributors to use `yarn`, so it's required to find what is causing this issue.

**Comment by fabiospampinato** [comment]
This is caused by the "prepublish" script I added, IIRC it's also called when the package is installed (non-sense), but they can't fix this for backwards compatibility. I think at some point they added support for a "prespublishOnly" script or something like that, I'll use that instead 👍

**Comment by fabiospampinato** [comment]
Yeah, regression fixed https://travis-ci.org/kenwheeler/cash/builds/441343806?utm_source=github_status&utm_medium=notification
