### ISSUE TITLE
[Critical] IE11: the element is emptied after creating another one

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#218]
### Current behavior

This one is nasty, should be fixed asap since there's still quite significant number of IE11 users out there.

This code

```js
const span = $('<span>CONTENT</span>')
console.log(span.html())
$('<div>')
console.log(span.html())
```

Produces

```js
"CONTENT"
"" // <-- !!!
```

### Expected behavior

```js
"CONTENT"
"CONTENT"
```

### Live demo

https://jsbin.com/vilexenodu/1/edit?html,js,console (Open in IE11)

@fabiospampinato please, if it's possible prioritize fixing this issue. Thank you.

**Comment by fabiospampinato** [comment]
Fixed in v2.3.7.

That actually had nothing to do with malformed html, I'm not sure how the DOM is supposed to work according to the spec, but if I had to guess we hit an IE 11 bug.

That was a nice catch, thank you 👍

**Comment by limonte** [comment]
Yay! Confirming that the fix is working for my project.

I so much appreciate the speed of your feedback @fabiospampinato 🙇 I did't find any info in your GitHub profile how to make a donation for your work, does https://www.paypal.me/fabiospampinato work for you?

**Comment by fabiospampinato** [comment]
> Did't find any info in your GitHub profile how to make a donation for your work, does https://www.paypal.me/fabiospampinato work for you?

I'm not quite sure how to answer this 😂 It's like getting your first pull request, but for donations.

Yes paypal.me works for me, but I'm also not in need of money, it's perfectly fine for me if you decide to donate those money to a more worthwhile cause, like wikipedia https://donate.wikimedia.org. Do what you think it's best. 

Thank you!

**Comment by limonte** [comment]
> I'm not quite sure how to answer this 😂 It's like getting your first pull request, but for donations.

Well, congratulations with you first donation from grateful `cash` user 💰 🎉
