### ISSUE TITLE
2.3.8 wasn't published on npm

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#223]
https://www.npmjs.com/package/cash-dom

### Current behavior

![image](https://user-images.githubusercontent.com/6059356/47252095-770e6a00-d447-11e8-9885-79f5e19398e7.png)

### Expected behavior

[2.3.8](https://github.com/kenwheeler/cash/commit/d375e634d036cb190a78a4f4f3bffdb2d359c07b)

**Comment by fabiospampinato** [comment]
I forgot about it, it's now published 👍 

Thanks.
