### ISSUE TITLE
.css({ height: -10 }) Negative height should set height to 0px

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#227]
### Current behavior

`.css({ height: -10 })` does nothing.

### Expected behavior

`.css({ height: -10 })` should set height to `0px`. The same is applicable to `width`.

### Live demo with jQuery comparison

https://jsfiddle.net/Lqz038o7/2/

**Comment by limonte** [comment]
> This is potentially an expensive fix bytes-wise

That'll take around 100-200 bytes, IMO not a big deal.

> It's not worth it to align with jQuery

The only one way for `cash` to become popular is not to be just an "alternative" of jQuery, but a "painless replacement" for it. I was replacing `jQuery` with `cash` for one of my projects and debugging this issue took quite a while, can't say it was a pleasant experience.

**Comment by fabiospampinato** [comment]
> That'll take around 100-200 bytes, IMO not a big deal.

100/200b to the minified and gzipped build? That's the file I'm interested in, the unminified or ungzipped files don't matter.

> The only one way for cash to become popular is not to be just an "alternative" of jQuery, but a "painless replacement" for jQuery's core. I was replacing jQuery with cash for one of my projects and debugging this issue took quite a while, can't say it was a pleasant experience.

We sure want to make switching from jQuery as painless as possible, but `cash` will never a 100% drop-in replacement for it, not even for it's DOM manipulation methods.

**Comment by limonte** [comment]
> 100/200b to the minified and gzipped build? That's the file I'm interested in, the unminified or ungzipped files don't matter.

Since we both care about this project to stay fit, let's introduce automated check for the bundle size: https://github.com/kenwheeler/cash/pull/228

**Comment by DzigaV** [comment]
This is a patently absurd request, that adds no value for developers or end users, and strongly detracts from the reason why I chose Cash over jQuery in the first place.

**Comment by fabiospampinato** [comment]
I think this is out of scope. Negative widths/heights are nonsensical and one shouldn't set them in the first place. 

We could have added support for this, but I think implementing this goes against `cash`'s goal of being "absurdly small" (yes, it doesn't add that many bytes to the bundle, but if we support this there's a whole lot of other things that we might support as well), and it will slow down the most common cases: setting positive heights/widths and using `$.fn.css` at all.

Maybe we should just list this in an hypothetical list of "common pitfalls" when switching from jQuery instead.

**Comment by limonte** [comment]
Thanks for the detailed response @fabiospampinato, I understand your point, you're probably right.

> Maybe we should just list this in an hypothetical list of "common pitfalls" when switching from jQuery instead.

That would be extremely useful. Wiki page?

**Comment by fabiospampinato** [comment]
> That would be extremely useful. Wiki page?

I don't like Wikis, I'm writing a markdown file instead. I'll let you now when it's published 👍

**Comment by fabiospampinato** [comment]
@limonte [here](https://github.com/kenwheeler/cash/blob/master/docs/migration_guide.md) you go.

**Comment by limonte** [comment]
Yay! Thanks a lot, @fabiospampinato 🙏
