### ISSUE TITLE
.next(selector) doesn't work

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#234]
First of all, `.next(selector)` isn't documented, so I'm not sure if this is a feature or a bug :)

If the behavior is supposed to be aligned with jQuery, it's a bug:

> If a selector is provided, it retrieves the next sibling only if it matches that selector.

### Live demo

https://jsfiddle.net/Lqz038o7/6/

### Current behavior

```html
<span id="initial"></span>
<strong></strong>
<div></div>
```

```js
$('#initial').next('div')
```

returns the collection with the `strong` node.

### Expected behavior

It should be empty collection because the next sibling (`strong`) doesn't match the selector (`div`)

**Comment by fabiospampinato** [comment]
> First of all, .next(selector) isn't documented, so I'm not sure if this is a feature or a bug :)

I'm not sure what you mean, it's here: https://github.com/kenwheeler/cash#fnnext-

Obviously we aren't rewriting a big portion of jQuery's API if that's what you meant.

You're testing against an older version of cash, support for a selector to `$.fn.next` has been added in v3 https://github.com/kenwheeler/cash/commit/849316968ae6eab58242a12bbee5d49c1622f078 and it seems to work from what I can see.

**Comment by limonte** [comment]
> I'm not sure what you mean, it's here: https://github.com/kenwheeler/cash#fnnext-

Can't see any docs on `selector` there.

> You're testing against an older version of cash, support for a selector to $.fn.next has been added in v3 8493169 and it seems to work from what I can see.

Any pans on release the v3 stable btw?

**Comment by fabiospampinato** [comment]
> Can't see any docs on selector there.

The readme says:

>  If you need more details about our API just check out jQuery's, while we don't implement everything that jQuery provides, everything what we do implement should be compatible with jQuery.

> Any pans on releasing v3 stable btw?

Of course, but I'd like to run jQuery's tests suite on it and try it on production before releasing it.

Can't really say when that will happen.

**Comment by limonte** [comment]
> Any plans on releasing v3 stable btw?

Good day @fabiospampinato, is the answer to this question still "Can't really say"?

**Comment by fabiospampinato** [comment]
No good estimates yet, but roughly I think I'll publish v3 after the first half of [this](https://github.com/notable/notable/milestone/2) milestone is done.
