### ISSUE TITLE
Event not triggered if using delegation

### ISSUE THREAD

**Issue by netfusion** [kenwheeler/cash#236]
Some events do not fire properly when delegation is used.
Examples are `mouseenter` and `mouseleave` but there may be more.

Test with cash: https://jsfiddle.net/dyo9xcq0/
Test with jQuery: https://jsfiddle.net/w62utcrj/

(Move the mouse over the elements and watch console output)

**Comment by fabiospampinato** [comment]
Some events do not bubble, and remember in the case of event delegation we are listening for events on the target element.

So instead of writing:

```javascript
$("#outer").on("mouseenter", "#inner", function(e) {
  console.log(e.currentTarget);
});
```

you should be writing:

```javascript
```

**Comment by netfusion** [comment]
A common use case would be a tooltip system which relies on attributes present on any kind of element.

`$("body").on("mouseenter", "[data-tooltip-content]", function(e) {
    $("#tooltip").text($(this).data("tooltipContent"));
});`

Im my case I am using an [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) now.

Maybe cash could use a MutationObserver to attach the delegated event handlers to matching newly created DOM elements instead of attaching them to the parent and cycling the DOM. This would solve this issue as well as #235.

**Comment by fabiospampinato** [comment]
Mutation Observers aren't available in IE10. This sounds interesting though, I'll see what can be done 👍

**Comment by fabiospampinato** [comment]
Fixed in https://github.com/kenwheeler/cash/commit/872f79da3f293eaf2b59d0e0de1c611f6f3bf28f. I'll publish a new beta as soon as I fix as few other problems.

It turned out that there are some events that do not bubble, and weirdly enough there are alternative events for them that do the same thing except that they bubble 🤷‍♂️ 

```
focus -> focusin
blur -> focusout
mouseenter -> mouseover
mouseleave -> mouseout
```

**Comment by fabiospampinato** [comment]
Btw this code:

```
$("body").on("mouseenter", "[data-tooltip-content]", function(e) {
    $("#tooltip").text($(this).data("tooltipContent"));  
});
```

Should have awful performance. mouseenter/mousover che fire tens of times every time you move the mouse. Also we have to traverse up the tree until we reach the body to check if any of those elements match `[data-tooltip-content]`, which is on its own a slow selector. 

You should instead find all those elements once, and maybe listen for the addition of other elements to the dom that match that selector (like you seem to be doing now?).
