### ISSUE TITLE
change() method

### ISSUE THREAD

**Issue by sinanerdem** [kenwheeler/cash#239]
jQuery has the `change()` method to detect changes on a form item (https://api.jquery.com/change/). I couldnt find the method in this library. Is there an alternative to this?

**Comment by fabiospampinato** [comment]
@sinanerdem jQuery provides some convenience methods for some events, we just treat them like any others:

```js
// jQuery
$('#foo').change ();
$('#foo').change ( event => {} );
// Cash
$('#foo').trigger ( 'change' );
$('#foo').on ( 'change', event => {} );
```
