### ISSUE TITLE
Can't run `npm install` on node 11.5 and npm 6.4.1. npm ERR! Command failed: /usr/bin/git checkout 4.0 npm ERR! error: pathspec '4.0' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by softwarecreations** [kenwheeler/cash#241]
### Current behavior

Using node 11.5 and npm 6.4.1
I created a new project called cash-test
`npm install --save-dev cash-dom`

Inside the cash-dom dir, I replaced pacco.json with https://github.com/kenwheeler/cash/blob/master/resources/pacco/collection_manipulation_traversal.json

Then I ran `npm install` inside the cash-dom dir.

```
npm WARN deprecated gulp-babili@0.1.4: babili has been renamed to babel-minify. Please update to gulp-babel-minify
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2018-12-22T11_03_15_390Z-debug.log
```

**Comment by fabiospampinato** [comment]
I'm not sure what this error is about. Can you reproduce it if you don't change pacco's configuration?

**Comment by fabiospampinato** [comment]
@indeedhat I don't think this is the case: https://github.com/paulmillr/chokidar/blob/0a46e6f3a12c13d427e08f289b3b4bb3790a2c69/package.json#L42-L44 . `fsevents` is optional.

**Comment by indeedhat** [comment]
yeah i just got back to this and you are right, the issue was pacco, i have manged to get the v2.0 version to install `npm i pacco@2.0` after that cash installed fine
