### ISSUE TITLE
3.0.0-beta.3 doesn't load in FF 64.0

### ISSUE THREAD

**Issue by softwarecreations** [kenwheeler/cash#242]
FF 64.0 Can't load https://cdnjs.cloudflare.com/ajax/libs/cash/3.0.0-beta.3/cash.min.js

SyntaxError: expected expression, got '<'

**Comment by fabiospampinato** [comment]
Just tried pasting that into FF64's dev console and it worked. Maybe you loaded it wrong or something? 

If you can craft some reproducible steps I'll reopen this issue.
