### ISSUE TITLE
Drop support for IE completely?

### ISSUE THREAD

**Issue by softwarecreations** [kenwheeler/cash#243]
I don't support any version of IE, even IE11 is JUNK
Edge versions 12-15 are also JUNK.

The pacco file comes with the option

"browsers": ["ie >= 10"],

Can cash be made even smaller by dropping support for the obsolete browsers?

**Comment by DzigaV** [comment]
Dropping IE11 is a silly idea. It's still the default browser in a large percentage of corporations.

**Comment by limonte** [comment]
Those "obsolete" browsers are **secure**, unlike Google Chrome. Its source code isn't open and who knows which information is being collected in the background. Google will do all the possible evil which is technically legal to collect as much data as possible.

For corporations as well as for government it's not possible to use third-party browsers **for security reasons**.

Here's the screenshot I made a couple of days ago:

![image](https://user-images.githubusercontent.com/6059356/50387161-8b4c3d00-06fe-11e9-9ccf-9fdb22bb4b38.png)

Google Chrome is closed, but the evil company is collecting my data.

**Comment by fabiospampinato** [comment]
When/if IE11's [usage](https://caniuse.com/usage-table) drops below to 0.5%, and if dropping support for it gives us any meaningful advantages, then maybe it will be dropped.
