### ISSUE TITLE
jQuery <-> Cash custom event compatibility

### ISSUE THREAD

**Issue by SamyCookie** [kenwheeler/cash#244]
Hi,

I found a bug with custom events triggered. `Cash` and `jQuery` can both catch custom events from vanilla JS `dispatchEvent / CustomEvent`. No problem. `jQuery.on` can catch custom event trigerred via `Cash.trigger`. No problem. BUT, `Cash.on` can NOT catch custom event trigerred via `jQuery.trigger`.

I know, I should not use both library in the same time, but I am making a soft migration of my code. During a time, there will be both library, so it will be pleasant if both library can work together (mainly with custom events)

**Comment by fabiospampinato** [comment]
@SamyCookie can you share some code that I can use to reproduce the issue?

**Comment by SamyCookie** [comment]
of course:
works
````javascript
jQuery('body').on('foo', () => console.log);
Cash('body').trigger('foo');
````
does not work
````javascript
Cash('body').on('foo', () => console.log);
jQuery('body').trigger('foo');
````

**Comment by SamyCookie** [comment]
It seems to be an edge case issue that can be resolved with https://github.com/kenwheeler/cash/issues/245#issuecomment-452329354.
Or maybe for my soft migration I will just change all `jQuery.trigger` first with `Cash.trigger`, and ONLY AFTER I will migrate `$.on` method.
@fabiospampinato thanks for your time
