### ISSUE TITLE
Cash (Jquery) special event hooks

### ISSUE THREAD

**Issue by kwuite** [kenwheeler/cash#245]
### Feature description

Implementation of the jQuery.event.special[ type ] to gain full control of existing events and create custom events.

I would like to be able to hook into the event handling mechanism which allows me to do large scale event manipulation, define my own events, hook into and spoof events by modifying the event objects.

Is this feature present in jQuery? Yes

Link to github code: 

- [focus in](https://github.com/jquery/jquery/blob/e743cbd28553267f955f71ea7248377915613fd9/src/event/focusin.js#L28)
-  [event](https://github.com/jquery/jquery/blob/e743cbd28553267f955f71ea7248377915613fd9/src/event.js#L166)

Docs: [Special Event Hook](https://learn.jquery.com/events/event-extensions/#special-event-hooks)

This implementation should also support this issue: https://github.com/kenwheeler/cash/issues/244

**Comment by fabiospampinato** [comment]
I don't think this is going to be implemented, one of Cash's goals is to remain as much small as possible, I personally never need this and didn't even know it existed.

**Comment by kwuite** [comment]
@fabiospampinato, it's real shame cause it helps for the use in frameworks like vue, react, blaze, etc. Also the notion that it has a big footprint on size is incorrect, we aren't talking about allot of code if I read the jquery github code correctly.

**Comment by fabiospampinato** [comment]
@kwuite there are a lot of features that we could add which require a small amount of code, but all together are probably not worth it adding. Also we are already very close to our self-imposed 5kb min & gz limit.

How would it help with things like React which comes with its own event system basically?

**Comment by SamyCookie** [comment]
for compatibility reasons (like #244), maybe it would be possible to create an additional outside hook library that extend Cash capacities with jQuery custom events ?

**Comment by fabiospampinato** [comment]
@SamyCookie you could definitely make a partial build with all the event-related methods excluded and override those manually.
