### ISSUE TITLE
deprecated Event methods used in Cash.trigger

### ISSUE THREAD

**Issue by SamyCookie** [kenwheeler/cash#247]
Per documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent
https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

Methods used at line
https://github.com/kenwheeler/cash/blob/1140772c108305fab889c55488a3756529beeb52/src/events/trigger.ts#L22-L23
seems to be deprecated

Consider to use [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) to pass data in the event cleanly.

**Comment by fabiospampinato** [comment]
I'm closing this as even in IE11 `CustomEvent` instances can't be created with the `new` keyword, and I don't see those deprecated APIs we are using ever getting dropped in practice.
