### ISSUE TITLE
$.fn.hide|show do not restore the previous display value

### ISSUE THREAD

**Issue by SamyCookie** [kenwheeler/cash#248]
Hi,

I found a bug with methods `show`/`hide`.
If a hide an element with a specific display (`flex` for example) set with CSS, this display is not restored by the `show` method (`block` by default for `div` element, for example).
This behaviour is wrong, and is different than jQuery behaviour (which is correct).

**Comment by limonte** [comment]
@fabiospampinato is there any policy on which bug-fixes will be applied to `2.x`? E.g. I'm currently using the latest stable (`2.x`) and would appreciate this fix to be backported there as well.

**Comment by fabiospampinato** [comment]
@limonte unfortunately my time is limited, I can't maintain two separate branches, one of which I won't even use. Is there any reason for you not to switch to v3 when that's released as stable?

**Comment by limonte** [comment]
> Is there any reason for you not to switch to v3 when that's released as stable?

Of course, I will, but I'm not sure for how long it'll be in beta (there's no release schedule afaik).

**Comment by limonte** [comment]
> unfortunately my time is limited

And I know why :) people I following quite often starring your new shiny project:

![image](https://user-images.githubusercontent.com/6059356/50904261-8b4f7b00-1428-11e9-853e-5fc25221e745.png)

**Comment by fabiospampinato** [comment]
@limonte yeah that kept me quite busy lately, and it's probably going to keep me busy for a while given the amount of interest it generated.

There's no schedule, but as soon as I'll switch [Svelto](https://github.com/svelto/svelto), my UI framework, to cash v3 and check that everything works across platforms I'll make a release. I think it will take at least 3 months, but my time estimates are a bit fuzzy so I'm not sure how much that's worth.
