### ISSUE TITLE
Just a thanks

### ISSUE THREAD

**Issue by jasonmunro** [kenwheeler/cash#251]
Hello!
Just wanted to say thanks for this library. I have been happily using Zepto in my software for a while (5 years), but the lack of updates has been concerning. Also smaller is better for my use case :). Aside from the lack of AJAX support, I only had to recreate 6 jquery methods (all of which are pretty simple to do) to get cash working, and replacing my single call to $.ajax with native XHR was not difficult. 

The following is barely tested and specific to my use case (and pretty hacky), but maybe useful to someone:
```
$.inArray = function(item, list) {
    for (var i in list) {
        if (list[i] === item) {
            return i;
        }
    }
    return -1;
};
$.isEmptyObject = function(obj) {
    for (var key in obj) {
        if (obj.hasOwnProperty(key)) {
            return false;
        }
    }
    return true;
};
$.fn.submit = function() { this[0].submit(); }
$.fn.focus = function() { this[0].focus(); };
$.fn.serializeArray = function() {
    var parts;
    var res = [];
    var args = this.serialize().split('&');
    for (var i in args) {
        parts = args[i].split('=');
        res.push({'name': parts[0], 'value': parts[1]});
    }
    return res;
};
/* requires the caller capturing the return value, not sorted in place */
$.fn.sort = function(sort_function) {
    var list = [];
    for (var i=0, len=this.length; i < len; i++) {
        list.push(this[i]);
    }
    return $(list.sort(sort_function));
};
```
Anyway, thanks again! I have only spent a few hours on the conversion but pretty sure we will switch to cash once I get it all sorted.

**Comment by DzigaV** [comment]
Yeah, I really love Cash. Ken and Fabio have done an amazing job. It's just what I wanted.

I've really enjoyed writing my own 5-line utility functions, instead of importing some 300 line jQuery library to do the job.

**Comment by fabiospampinato** [comment]
I'm glad you guys like it :)
