### ISSUE TITLE
Does anyone have experience with switching jQuery for Cash in Zurb Foundation?

### ISSUE THREAD

**Issue by Revisor** [kenwheeler/cash#253]
Hi, I really like Cash and we're thinking of switching over to it from jQuery. However we use the Zurb Foundation framework [which requires jQuery](https://foundation.zurb.com/sites/docs/javascript.html).

Does someone have experience with switching from jQuery to Cash in Foundation? I'll try it myself but maybe someone has already gone through this path before.

**Comment by fabiospampinato** [comment]
I'm closing this as it's not really an issue. If people who have been notified by the creation of this issue would like to respond they will be free to do so. Perhaps StackOverflow might be a better place for asking such questions.

In the meantime I'd recommend you reading our [migration guide](https://github.com/kenwheeler/cash/blob/master/docs/migration_guide.md).

**Comment by neilD2** [comment]
Hi @Revisor , did you have an luck doing this?
