### ISSUE TITLE
$(...).prevAll is not a function

### ISSUE THREAD

**Issue by tomassentkeresty** [kenwheeler/cash#254]
### Current behavior
version: 2.3.9
I get an error that `prevAll()` is not defined. I tested also `prev()` and that function works. 

```
$(element).prevAll() // throws: Uncaught TypeError: $(...).prevAll is not a function
```

### Expected behavior

Function `$(element).prevAll()` should be defined.

**Comment by fabiospampinato** [comment]
It is defined, but it's not available before v3, you'd probably want to use that version: `npm i cash@3.0.0-beta.3`
