### ISSUE TITLE
The API documentation is not synced with the installation instructions

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#256]
Installation instructions from README:

```sh
npm install cash-dom --save-dev
```

This will install the latest stable which is v2.

---

At the same time, the API docs are representing v3 functionality.

This brings confusions, e.g. #254 #234

**Comment by limonte** [comment]
The suggested solution: release v3 stable so people will battle-test it. The beta period for small projects is normally 2-4 weeks. 3.0.0-beta.3 was released 3 months ago which is mature enough.

The alternative solution:

```sh
npm install cash-dom@last --save-dev
```

**Comment by limonte** [comment]
> npm install cash-dom@last --save-dev

Oops, typo here, should be 

```sh
npm install cash-dom@next --save-dev
```

**Comment by fabiospampinato** [comment]
🤔 Maybe we should just release cash v3, after all it's backed by a better test suite already and it fixes some bugs. I'm pretty busy right now, but once [this](https://github.com/notable/notable/milestone/1) list of bugs is emptied I'll try to get this done.

**Comment by limonte** [comment]
Good day @fabiospampinato!

As I understand correctly, "Next" was done 2 days ago, but v3 stable hasn't been released. Did you change your mind about it?

**Comment by fabiospampinato** [comment]
Hey, I haven't changed my mind about this, but I have a bit of a backlog to take care of, which also includes this issue, and I didn't have much time for the computer yesterday, just have a little more patience 👍

**Comment by limonte** [comment]
Roger, thanks!

**Comment by fabiospampinato** [comment]
Just released 🎉

**Comment by limonte** [comment]
Love the consistency of your work! Here's the small sign of appreciation from me: 

![image](https://user-images.githubusercontent.com/6059356/54512856-441cc380-495e-11e9-96fb-b0d3455d5de5.png)

Have a great day @fabiospampinato and keep doing great things :muscle: :muscle: :muscle:

**Comment by fabiospampinato** [comment]
Thank you 😃
