### ISSUE TITLE
How to use cash 3.x with Typescript?

### ISSUE THREAD

**Issue by sqal** [kenwheeler/cash#257]
Hi. I have a question regarding using this library in Typescript project. I've installed latest version of cash-dom@3.0.0-beta.3, I also use latest version of Typescript (3.3.3333)

here's my tsconfig.json

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",

    "strict": true,
    "strictPropertyInitialization": false,
    "noImplicitReturns": true,
    "noImplicitAny": true,

    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "forceConsistentCasingInFileNames": true,

    "baseUrl": ".",
    "moduleResolution": "node",
    "esModuleInterop": true
  }
}
```

but when I import cash I see this error:

```
File 'xxx/node_modules/cash-dom/dist/cash.d.ts' is not a module.ts(2306)
```

![Screenshot](https://i.imgur.com/n5xnaRC.png)

So Cash typings doesn't work at all. Am i missing something in my tsconfig file? Could anyone explain what is the problem here? Appreciate your help Thanks

**Comment by fabiospampinato** [comment]
There's an `export default cash` line missing from our types, thanks for reporting the issue 👍
