### ISSUE TITLE
$(selector, context) context can't be selector

### ISSUE THREAD

**Issue by bato3** [kenwheeler/cash#258]
`$(selector, context)` context can't be selector

version: 3.0.0-beta.3

### Current behavior

`$('.proggres', '#fa-201-18')` don't work

`$('.proggres', $('#fa-201-18'))`, `$('#fa-201-18 .proggres')`  Works OK

**Comment by fabiospampinato** [comment]
I don't think this is worth implementing, it only saves you 3 characters and not having it encourages you to cache the result of that selector instead, which is probably something one should do 🤔 

Also in jQuery v3 having a string selector doesn't seem to be supported either:

<img width="789" alt="Screen Shot 2019-03-16 at 01 37 19" src="https://user-images.githubusercontent.com/1812093/54468387-52b38100-478c-11e9-9706-73723bcccde0.png">

Maybe that was only available in jQuery 1.x or something. Or maybe the docs are actually wrong 🤔

**Comment by bato3** [comment]
This is not about these few characters, but about the time spent on finding why it does not work after changing jQuery -> Cash

And this work on `"jquery": "^3.3.1",`

**Comment by fabiospampinato** [comment]
That's a good point, I've update the readme https://github.com/kenwheeler/cash/commit/c55287b877e9874234c5982bb385e1c026ac4832

Hopefully while that's not a perfect solution maybe that's a decent implement.
