### ISSUE TITLE
jQuery uncompatibility report  (migration plugin)

### ISSUE THREAD

**Issue by bato3** [kenwheeler/cash#259]
### Feature description
A tool that help migrate from jQuery by detecting and reporting incompatible syntax. Aka: teach me how to write good code.

Mode:

- report to browser console
- report to server

### Feature motivation
Over the years using jQuery, many people gained bad habits, eg. https://github.com/kenwheeler/cash/issues/258

There are also some methods available for backward compatibility, which unnecessarily burden the library, eg. [`$().click()`](https://api.jquery.com/click/)

Is this feature present in jQuery? Yes/No: **No**

**Comment by fabiospampinato** [comment]
Duplicate of #75 

I don't see this getting implemented, but if somebody would like to take a shot a this and can produce a quality utility that would be great.
