### ISSUE TITLE
Collections should be iterable

### ISSUE THREAD

**Issue by SamyCookie** [kenwheeler/cash#262]
AFAIK, this is not a documented behavior in jQuery, but in practical it works with jQuery > 3.

This is a VERY useful enhancement that allow to use `for of` syntax with `Cash` objects, and make more modern code than using always the old `$.each` method.

Here is my own implementation:
```javascript
Cash.fn[Symbol.iterator] = function *iterator() {
	for (let i = 0, len = this.length; i < len; i++) {
		yield this[i];
	}
}
```

**Comment by fabiospampinato** [comment]
It sounds like something useful, and the implementation would be pretty minimal too:

```js
if ( typeof Symbol === "function" ) {
  cash.fn[Symbol.iterator] = Array.prototype[Symbol.iterator];
}
```

Thanks for the suggestion!

**Comment by SamyCookie** [comment]
I like your implementation more minimal than mine. But why testing the `Symbol` type ?
