### ISSUE TITLE
Please add focus() and blur()

### ISSUE THREAD

**Issue by dylankil** [kenwheeler/cash#263]
### Feature description

The ability to focus or not focus on a Cash element.

### Feature motivation

Make life easier.

Is this feature present in jQuery? Yes

**Comment by fabiospampinato** [comment]
I don't think those methods fit well with our goals, you can add them yourself (I haven't tested it):

```js
const $ele = $('.foo');
$.fn.focus = function () {
  if ( this.length && this[0].focus ) this[0].focus ();
  return this;
};
$.fn.blur = function () {
  if ( this.length && this[0].focus ) this[0].blur ();
  return this;
}
```

**Comment by limonte** [comment]
I have the need for `focus()` and `blur()` as well and implementing the code mentioned by @fabiospampinato 

@fabiospampinato could you please elaborate a bit on

> I don't think those methods fit well with our goals

You most probably have reasons behind that statement, but they're unclear (at least for me) and it would be great to clarify them for the community.

**Comment by fabiospampinato** [comment]
> @fabiospampinato could you please elaborate a bit on "why" of

Sure. Since our goal is to be "absurdly small" we can't include non-essential methods. Obviously people will have different opinions on what's essential, for instance if you need `$.fn.focus` but don't need `$.fn.wrap` then `$.fn.focus` will be more essential to you.

Maybe these sorts of methods should be implemented but not included by default in our bundles. So that if people wanted to they could compile cash themselves and include them, but also we could point at a reference implementation for those that need them 🤔

**Comment by dylankil** [comment]
While refactoring a web app to move away from using jQuery. These two functions caused the most errors, given the accessibility standards that need to be met. I could use document.getElementByID('elementID'), but that begs the question of using Cash in the first place.

**Comment by fabiospampinato** [comment]
@dylankil Wouldn't re-defining those methods yourself be a better solution then refactoring all the code that uses those methods?

**Comment by dylankil** [comment]
Sure, just pointing out a pain-point in an otherwise easy refactor of quite a large application.

**Comment by fabiospampinato** [comment]
I've just added a reference implementation for those shorthand methods [here](https://github.com/kenwheeler/cash/blob/master/src/extra/shorthands.ts). It can be enabled by removing [this](https://github.com/kenwheeler/cash/blob/8b4a9b284a6d71dc2d11dd6048686150c0df1d9b/pacco.json#L5) line and re-bundling the app with `npm run build:deploy`.
