### ISSUE TITLE
Requesting getScript to be available in cash

### ISSUE THREAD

**Issue by y1** [kenwheeler/cash#264]
I'm frequently using _jQuery_ as dependency management by include another JavaScript file using `getScript`.

This feature present in _jQuery_ but not yet in _cash_.

So I'm requesting this feature to be available in _cash_.

**Comment by fabiospampinato** [comment]
There's a reference implementation for this [here](https://github.com/kenwheeler/cash/blob/master/docs/migration_guide.md#parsing-script-tags).

I don't think this will be included into the core, since our goal is to be "absurdly small" and not everyone will need `$.getScript`.

**Comment by fabiospampinato** [comment]
I've just added a reference implementation for those shorthand methods [here](https://github.com/kenwheeler/cash/blob/master/src/extra/get_script.ts). It can be enabled by removing [this](https://github.com/kenwheeler/cash/blob/77f6b4238d5e44b34388b6a711c15fcfa23bf1e8/pacco.json#L5) line and re-bundling the app with `npm run build:deploy`.

**Comment by y1** [comment]
Thank you very much for the feedback. I appreciate it.

**Comment by y1** [comment]
Can you do a basic demo of it?

I always get error `Uncaught SyntaxError: Unexpected token :` on line:
`function getScript ( url: string, success?: Function ): void {`

This is what I did:

```
		$(function () {
			// @require core/cash.ts
			// @require core/variables.ts

			function getScript ( url: string, success?: Function ): void {

				const script = doc.createElement ( 'script' ),
					$anchor = cash ( 'script' );

				script.async = true;
				script.src = url;

				if ( success ) script.onload = () => success ();

				$anchor.before ( script );
			}

			interface CashStatic {
				getScript ( url: string, success?: Function ): void;
			}

			cash.getScript = getScript;

			$.getScript("script.js");
		});

```

I'm using latest version cash 3.1.0 and `cash.ts`, `variables.ts` & `find.ts` all are inside the same directory.

Thank you.
