### ISSUE TITLE
Keep the minified & gzipped bundle under 5KB

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#266]
![image](https://user-images.githubusercontent.com/6059356/54857987-f52eaf80-4d0a-11e9-93be-02673de5d64e.png)

I brought `bundlesize` check in https://github.com/kenwheeler/cash/pull/228 so this is kinda my fault :)

Here's the thing:

![image](https://user-images.githubusercontent.com/6059356/54858776-a8010c80-4d0f-11e9-98a1-55fd25fca2b3.png)

181 deps for the utility that should perform the simple comparison of two numbers and exit with `1` if needed. That's right, it's how we are doing things in JS ecosystem.

The best part is that it doesn't work:

![image](https://user-images.githubusercontent.com/6059356/54858838-f6161000-4d0f-11e9-8680-507a5f64342c.png)

Reported here: https://github.com/siddharthkp/bundlesize/issues/188#issuecomment-475818611 and here https://github.com/siddharthkp/bundlesize/issues/289 (bundlesize has 0 tests :man_facepalming: :man_facepalming: :man_facepalming: )

I guess they need to add a couple of hundreds more dependencies to make it work, let's see.

---

The lesson I should learn here: do not blindly bring tools which have a lot of stars (because they were hyped by Google devs), ensure their quality by yourself.

**Comment by fabiospampinato** [comment]
Yeah I noticed that, currently we are exceeding the limit by about 20B, and I don't really have the time to try to squeeze some more bytes out of the bundle. If anybody would like to try doing so, without sacrificing performance I'd be happy to consider some PRs, but I don't think there's too much margin for improvement here, pretty much everything I could think of I've tried already.

**Comment by limonte** [comment]
I don't see any ways to squeeze the bundle size, IMO we should just update README and bundlesize check with up-to-date numbers:

![image](https://user-images.githubusercontent.com/6059356/54867707-0075ef80-4d8c-11e9-8928-a961043c9730.png)

**Comment by limonte** [comment]
Instead of hardcoded it'll make more sense to use something like https://badgen.net/#badgesize

**Comment by fabiospampinato** [comment]
I've updated the table, but I'm keeping this open as I would like to bring back the bundle size under 5KB.

**Comment by tunnckoCore** [comment]
Just to suggest, there is also [size-limit](https://github.com/ai/size-limit). If that's the need.

Regarding the badges, it's always a cool thing. There also Packagephobia and Bundlephobia badges on the Badgen.

**Comment by fabiospampinato** [comment]
We are now down from ~5220 bytes to 5010 bytes, hopefully soon we'll get back below the 5kb threshold, easily achievable is support for IE10 gets dropped #315 .

**Comment by fabiospampinato** [comment]
We are at 4986 bytes right now: https://github.com/kenwheeler/cash/commit/6f203a55bf70ff9bc5f6c0a3914e3e63bcc0b042

So I'm closing this, although I don't think we'll remain below the 5kb mark forever, but I don't want the library to ever reach 6kb, possibly not even 5.5kb.

**Comment by tunnckoCore** [comment]
Not that absurdly small, but yea acceptable. :)

I was fascinated by [ki.js](https://github.com/dciccale/ki.js) and [ki.extend.js](https://github.com/james2doyle/ki.extend.js) before years. It's kind of sad that they are not "maintained" but in same time.. it's so small that there's nothing to maintain :D You can get inspiration.

**Comment by fabiospampinato** [comment]
@tunnckoCore I'd say it's way more than acceptable. I'd say between being "acceptable" and "absurdly small" there must be at least a 40% in size reduction or something, right? Why don't you show me how to reduce the size of the library by a mere 10% first, which should be easily achievable if the library was only "acceptably" small.

**Comment by fabiospampinato** [comment]
Also I can't bloody change the description since I'm not the repo owner and I can't manage to get this library transferred to me. Maybe "absurdly" doesn't fit it anymore.
