### ISSUE TITLE
getScript error: "Uncaught SyntaxError: Unexpected token :"

### ISSUE THREAD

**Issue by y1** [kenwheeler/cash#267]
I'm using latest version cash 3.1.0 and `cash.ts`, `variables.ts` & `find.ts` all are inside the same directory.

I always get error `Uncaught SyntaxError: Unexpected token :` on line:
`function getScript ( url: string, success?: Function ): void {`.

Removing `$.getScript("script.js");` also still giving the same error.

This is what I did:

```
<head>
	<script src="cash.min.js"></script>
	<script>
		$(function () {
			// @require core/cash.ts
			// @require core/variables.ts

			function getScript ( url: string, success?: Function ): void {

				const script = doc.createElement ( 'script' ),
					$anchor = cash ( 'script' );

				script.async = true;
				script.src = url;

				if ( success ) script.onload = () => success ();

				$anchor.before ( script );

			}

			interface CashStatic {
				getScript ( url: string, success?: Function ): void;
			}

			cash.getScript = getScript;

			$.getScript("script.js");
		});
	</script>

</head>

```

Any suggestion or demo are really appreciated.

**Comment by fabiospampinato** [comment]
That code is TypeScript, not JavaScript, that's why it doesn't work for you. You can compile it to JS on the fly [here](https://www.typescriptlang.org/play/), this would be the result:

```js
function getScript(url, success) {
    var script = doc.createElement('script'), $anchor = cash('script');
    script.async = true;
    script.src = url;
    if (success)
        script.onload = function () { return success(); };
    $anchor.before(script);
}
```
