### ISSUE TITLE
Find an id inside a context

### ISSUE THREAD

**Issue by prsdta** [kenwheeler/cash#270]
Hi, I've been trying out this library and the jQuery codebase I was trying it on made me discover what I imagine being a bug in cash.

### Current behavior

When trying to find an element with an id inside a context, cash throws.
e.g:
```js
$("#some-id", someHTMLElement);
// >  TypeError: b.getElementById is not a function   cash.min.js:4:142
```

This is probably because `getElementById` is only available on the `Document` prototype ([ref on MDN](https://developer.mozilla.org/en-US/docs/Web/API/document/getElementById)), and I imagine cash doesn't override correctly the context in this case?

### Expected behavior
No error and a cash instance, as jQuery does it.

Not sure if there's a deliberate difference in the cash API but the Readme doesn't seem the indicate there is. And I haven't seen a similar issue so here it is.

**Comment by fabiospampinato** [comment]
Is `someHTMLElement` an element of the current document or something different? (document fragment, another document...).

**Comment by prsdta** [comment]
My original use case is to find content in same-origin iframes, but the problem also arises with a Element from the same document.

I made a simple codesanbox because this is probably the most direct way to describe it (and also to be sure there were no conflict):
https://codesandbox.io/embed/wwxj334xkw

**Comment by fabiospampinato** [comment]
> My original use case is to find content in same-origin iframes

Can you share some code? I think you should be able to do that this way:

- `$( '#foo', $('iframe').contents () )` or
- `$('iframe').contents ().find ( '#foo' )`

Regarding selecting by ID from an element in the current document I don't think it makes much sense to support this use case. IDs must be unique, so passing in an explicit context which is in the current document anyway serves no purpose.

**Comment by prsdta** [comment]
I did retry with iframes and it works indeed. In my original code, elements with the same id could appear in several iframes, so depending on the case I'd use a parent element I have in scope as the context argument. I guess I'd have to use the `.ownerDocument` property to fix it.

I agree overall it's not a really useful case, my point was more about jQuery being idiot-proof about it and whether or not you'd want to replicate that “feature”.

**Comment by fabiospampinato** [comment]
Even if there are multiple elements with the same ID disseminated into multiple iframes I don't think you can selected them all just by running `$('#myid')`.

I'm closing this as I don't think the performance penalty of the extra check is worth it.
