### ISSUE TITLE
typescript default import issue

### ISSUE THREAD

**Issue by YanirShahak** [kenwheeler/cash#271]
I'm importing cash like so:
`const $ = require('cash-dom') as CashStatic;`

I'm able to get intellisense support from VSCode this way and development is a joy.
However, at runtime, $ doesn't seem to be a function but rather an object with a .default property which is actually the function i'm supposed to call.

I'm using webpack to bundle my stuff.

Any idea how i can get around this default issue?

**Comment by fabiospampinato** [comment]
It seems WebPack is loading the esm build of Cash, so you either import it like this:

```
import $ from 'cash'
```

or like this:

```
const $ = require ( 'cash-dom' ).default;
```

Let me know if that solves the issue 👍
