### ISSUE TITLE
Convert to ESM

### ISSUE THREAD

**Issue by TheLarkInn** [kenwheeler/cash#272]
### Feature description
The smallest jQuery implementation is the one that gets treeshaken :smirk: 

### Feature motivation

So I don't have 90% of my JavaScript bundled marked as unused because I want to import one method from cash-money over here. 

Is this feature present in jQuery? Yes/No
No

**Comment by fabiospampinato** [comment]
I'm not very familiar with tree shaking, I have a few concerns with this:

1. Keeping our minified bundle [here](https://github.com/kenwheeler/cash/blob/master/dist/cash.min.js) as small as possible is important to us, wouldn't exporting and importing all our components individually add a significant amount of useless require calls to the bundle?

2. We have a few methods exported as `$.*` (e.g. `$.isFunction`), I can see how those could easily be imported individually when needed, but everything else relies on selecting the elements to work on first with the main selector `$()` and is designed around providing a chainable API. For instance we can write this today:

```ts
import $ from 'cash-dom';
$('.foo').addClass ( 'asd' ).find ( 'li' ).remove ();
```

how would this piece of code translate to a tree shaking-enabled version of cash? The following looks awful to me, and most importantly it would be a very different API:

```ts
import {$, addClass, find, remove} from 'cash-dom';
const $foo = $('foo'); // We don't want to run this selector more times than necessary, so we cache it
addClass ( $foo, 'asd' );
const $li = find ( $foo, 'li' );
remove ( $li );
```

3. If I run `import {each} from 'cash-dom';` is that supposed to import `$.each` or `$.fn.each`? 

This doesn't seem practical to me, IMHO [partial builds](https://github.com/kenwheeler/cash/blob/master/docs/partial_builds.md) are a better options for cash.
