### ISSUE TITLE
Release partial build too

### ISSUE THREAD

**Issue by findow** [kenwheeler/cash#273]
I noticed that the library can have partial builds too, and you make an example of 4 different partial builds: would it be possible for you to distribute them too?
If I wanted them I would need to fork the project and run npm, instead having them already available would avoid these steps for other developers interested in these partial builds
Thanks
Regards

**Comment by fabiospampinato** [comment]
The thing about partial builds is that they allow you to use only what you need, but there are so many possible different partial builds that I don't think it would makes sense for us to publish them all.

**Comment by findow** [comment]
In fact I'm suggesting to release partial build only for the 4 given examples: more often than not I use only the methods of the combination collection + manipulation + traversal, it would be useless for me to have the full library

**Comment by fabiospampinato** [comment]
I don't think it's a good idea, but if you wanted to you can publish those yourself once and then import them in your projcets.

**Comment by findow** [comment]
The problem is that I should compile these myself each time you release a new version
I'm not going to insist more than this, but publishing the Partial Builds of the examples would even allow the users to see if the declared sizes in the table are correct or not

**Comment by findow** [comment]
There is no need to publish these partial builds on CloudFlare or jsDelivr, it is enough to have them in the dist folder of your repository

**Comment by fabiospampinato** [comment]
Sorry I don't think it's worth the effort on our side. If bundle is is a concern you should be making your own partial build which doesn't include anything more than you need.
