### ISSUE TITLE
RFC: removal of $.fn.data caching, $.hasData and $.fn.removeData

### ISSUE THREAD

**Issue by fabiospampinato** [kenwheeler/cash#274]
Right now we are more aligned with jQuery than other libraries, like Zepto, are with regards to the data-related methods:

- `$.fn.data`: the values retrieved by this function are cached, so if they are updated manually the retrieved value won't reflect the change and will always be the cached one.
- `$.hasData`: this function tells you if any data have been cached for a specific DOM node.
- `$.fn.removeData`: this method removes the existent data cache (if any).

I propose to remove the caching mechanism of `$.fn.data`, so that it will always fetch fresh values, and remove `$.hasData` and `$.fn.removeData`.

### Pros

- Currently the user must be aware of this caching mechanism at all times in order to avoid creating subtle bugs (I maintain this library and I just stumbled on an issue caused by this 🤦‍♂).

- This behavior makes it difficult/impossible for cash to work with UI libraries like React. In React a data-* attribute might get updated by React itself and previous DOM nodes will possibly be reused rather than be removed and re-created. This causes the data cache object of the previous element to be preserved on the next one, effectively meaning that `$.fn.data` is basically unusable with React.

- `$.hasData` and `$.fn.removeData` are only needed because of the caching mechanism, once that's removed we could remove these as well, simplifying the API a bit.

- Removing those methods and the caching mechanism would allow cash to be a bit smaller in size.

### Cons

- If you are retrieving very often a very expensive-to-parse data-* attribute (like a big JSON object or something) that doesn't actually get updated very often, this change will have some performance implications. IMO this situation practically never happens, data-* attributes are usually retrieved once and cached and/or if they are retrieved again often it's because they probably changed (in that case there would actually be a very very tiny performance improvement by removing the caching mechanism).

I'd argue the pros outweigh the cons and I propose to remove the caching mechanism from `$.fn.data` and remove `$.hasData` and `$.fn.removeData` in the next few days. This would be a major change so the library would have to be published as v4. 

What do you guys think? Is there any reason for keeping the library behaving like this that I've missed?

**Comment by limonte** [comment]
Even though this would be a breaking change, it'll probably affect a small percentage of `cash` users. My vote goes for simplifying things, the caching layer could be added by a developer on the app level in those rare cases when it's actually needed.
