### ISSUE TITLE
What would be the best way to force .data() to always return string values?

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#276]
The `.data()` method will return boolean values in case of `data-arg="true"` and `data-arg="false"`

Live demo: https://jsfiddle.net/5e8uqh3b/1/

Do you have any advice on how to force `.data()` to always return string value?

**Comment by fabiospampinato** [comment]
@limonte use `attr` instead. If you don't call `data` without arguments you might want to do something like this:

```js
$.fn.data = function ( name, value ) {
  return this.attr ( `data-${name}`, value );
};
```

**Comment by limonte** [comment]
Thank you @fabiospampinato for your advice!

I ended up with 

```js
$.fn.data = function (name, value) {
  return typeof value === 'undefined' ? this.attr('data-' + name) : this.attr('data-' + name, value)
}
```

**Comment by fabiospampinato** [comment]
@limonte also keep in mind that there are a few differences between `attr` and `data`, namely you can't pass to `attr` JSON-stringifiable objects.

That check for undefined could probably be removed once #277 is fixed.

**Comment by limonte** [comment]
> That check for undefined could probably be removed once #277 is fixed.

I don't think so. `cashElement.attr('data-word', undefined)` and `cashElement.attr('data-word')` are different things: https://jsfiddle.net/Lr9kvt4w/

**Comment by fabiospampinato** [comment]
> I don't think so. cashElement.attr('data-word', undefined) and cashElement.attr('data-word') are different things: https://jsfiddle.net/Lr9kvt4w/

Right, jQuery's (and now Cash's as well) behavior when `undefined` gets passed is pretty weird.
