### ISSUE TITLE
Property 'submit' does not exist on type 'EleLoose'. ts(2551)

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#296]
I'm trying to extend cash with the `submit()` method:

```ts
declare module 'cash-dom' {
  interface Cash {
    submit(): Cash
  }
}

$.fn.submit = function () { 
  this[0] && this[0].submit(); 
  return this 
}
```

and getting this error:

![image](https://user-images.githubusercontent.com/6059356/62422752-0c6da880-b6c0-11e9-95b7-83a4036ab250.png)

I believe `EleLoose` should have `HTMLFormElement` as well.

**Comment by fabiospampinato** [comment]
This is a rough edge of the library, I'll try to smooth it out 👍

**Comment by fabiospampinato** [comment]
Fixed in v3.1.4.

Check out [this](https://github.com/kenwheeler/cash/blob/master/docs/extending_cash.md) little guide on how to extend Cash when using TypeScript.

Also you might want to write your `submit` method more like this:

```ts
import $ from 'cash-dom';
import {Cash} from 'cash-dom';

declare module 'cash-dom' {
  interface Cash {
    submit (): Cash
  }
}

$.fn.submit = function ( this: Cash ): Cash {
  if ( this[0] ) this[0].submit ()
  return this;
}

$('form').submit ();
```

Notice how both the `this` type (this syntax is provided by TypeScript) and the return type are strictly typed.

**Comment by limonte** [comment]
Thank you @fabiospampinato!

I'm trying the code you've suggested and getting this error:

![image](https://user-images.githubusercontent.com/6059356/62472243-f38bf280-b7a6-11e9-9b95-4979e82e0000.png)

**Comment by fabiospampinato** [comment]
🤔 stupid TypeScript. Maybe you have to assign `this[0]` to a variable first in order to make TS happy, or you can use the [bang operator](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator) (which is quite ugly IMHO) and write `this[0]!.submit ()`

**Comment by fabiospampinato** [comment]
You can also disable `strictNullChecks`, but I don't recommend it.
