### ISSUE TITLE
Core function matches is not extandable

### ISSUE THREAD

**Issue by xronos-i-am** [kenwheeler/cash#297]
### Feature description

Could you please add ability to extend function **matches**

### Feature motivation

I use cash to replace jQuery in existing project with some legacy jquery plugins. Vendor code uses some specific sizzle selectors like **:not** or jquery **:hidden**. At the moment function **matches** cant be extended because it used in closures (**function getCompareFunction**, **function on**)

If it would be done, i extend function like that (i use cash.esm.js):
```javascript
cash.matches = (ele, selector) => Sizzle.matchesSelector(ele, selector)
```

**Comment by xronos-i-am** [comment]
Same for function **find**

**Comment by fabiospampinato** [comment]
Using the version of the function accessible from the closure allows us to squeeze a few more bytes out of our bundles and gives us an extra drop of performance.

Maybe the cons outweigh the pros, but in this scenario I think a better solution would be to override `$` entirely:

```ts
const _$ = $;
window.$ = function ( selector, context ) {
  return _$ ( Sizzle ( selector, context ) );
};
```

Would that work for you?

**Comment by fabiospampinato** [comment]
Overriding `$` won't work though for `find` though, you'll have to override that too.

**Comment by fabiospampinato** [comment]
Overriding methods will be very tedious if you also need to support non-standard selectors to be passed as arguments to some of the collection methods 🤔

I don't know, I feel this request is a bit out of scope, part of Cash being modern comes from supporting only standard selectors, you should stop using custom selectors, e.g. `$('foo:visible')` => $('foo').filter ( isVisible )` or `$('foo').filterVisibile ()` or something.

> I use cash to replace jQuery in existing project with some legacy jquery plugins

Can't you patch those plugins instead?

**Comment by xronos-i-am** [comment]
> Can't you patch those plugins instead?

Too big codebase, i.e. FancyBox (the main promlem). I replace plugins one by one with vanilla analogs, but not all of them has appropriate alternatives

**Comment by xronos-i-am** [comment]
> Overriding `$` won't work when using `$.fn.find` though, you'll have to override that too.

You are right, I have the following code now:
```javascript
const htmlRe = /<.+>/
Cash.prototype.init = (selector, context) => {
  if (selector instanceof Cash) {
    // $($(document.body))
    return selector
  } else if (cash.isString(selector) && htmlRe.test(selector)) {
    // $("<div>")
    return new Cash(selector, context)
  } else if (selector && (selector.nodeType || selector === window)) {
    // $(document.body)
    return new Cash(selector, context)
  } else {
    return new Cash(Sizzle(selector, context))
  }
}
const cashExtended = Cash.prototype.init
cashExtended.fn = cashExtended.prototype = Cash.prototype
Object.keys(cash).forEach(k => (cashExtended[k] = cash[k]))

const origFind = Cash.prototype.find
Cash.prototype.find = function find(selector) {
  return Cash.prototype.init(selector, this)
}
```

**Comment by fabiospampinato** [comment]
>  i.e. FancyBox (the main promlem)

Jeez, Fancybox alone weighs ~70kb once minified, that's like 5 times the entirety of Cash. Perhaps you should consider switching to something else while you're at it 😄 

I'm not sure how this problem should be addressed. I'd rather not expose internal functions (which jQuery isn't exposing either).

We could expose the `find` function as `Cash.qsa`, similarly to how Zepto is exposing its selector function as `Zepto.qsa`, but the thing is we are actually selecting elements by id [here](https://github.com/kenwheeler/cash/blob/master/src%2Fcore%2Fcash.ts/#L19-L20) for performance, so the `find` function does not contain our entire selection logic.

**Comment by xronos-i-am** [comment]
It's sad. Cash can't be used as replacement of jQuery for existing projects. There are thousands of jquery pluging in the wild

**Comment by fabiospampinato** [comment]
Well, it can, me and other folks are doing it. But Cash isn't a _drop-in_ replacement for jQuery. 

I think jQuery in order to properly implement its custom selectors is importing an entire selector engine, which alone weighs more than Cash.

If anybody can think of a better way to improve Cash compatibility with jQuery's custom selectors I'm all ears.

**Comment by fabiospampinato** [comment]
Closing this in favor of #316
