### ISSUE TITLE
$.fn.data quotes strings

### ISSUE THREAD

**Issue by bananatron** [kenwheeler/cash#298]
### Current behavior

```
$('#lol').data('whoah', 'yeah')
// <div id="lol" data-whoah='"yeah"'></div>

```
### Expected behavior
```
$('#lol').data('whoah', 'yeah')
// <div id="lol" data-whoah="yeah"></div>
```

I was puzzled as to why my data selectors weren't working, and this seemed to be the reason.

Assuming this is actually an issue (and I'm not missing something) it seems the culprit is here: https://github.com/kenwheeler/cash/blob/612635aae630afe967569799607f5063bc290e8d/src/data/helpers/set_data.ts#L7

🙏

**Comment by fabiospampinato** [comment]
🤔 This is a little inconsistency with jQuery, however I think it allows us to ship smaller bundles, and generally attribute I think CSS selectors in the form of `[data-foo="foo"]` shouldn't be used because they are slow. 

If we can align more with jQuery without sacrificing bundle sizes it'd be great, PR welcome.

**Comment by bananatron** [comment]
Perhaps they shouldn't be used in CSS, but I think this will cause inconsistencies in JS as well that one wouldn't expect (I'm now using setAttribute in my project as a result of this interaction):

```
$('#foo').data('lol', 'yay')

// In DOM: <div id="foo" data-lol="'yay'"></div>

$('#foo').data('lol') == 'yay' // true
$('#foo')[0].dataset.lol == 'yay') // false
$('#foo')[0].getAttribute('data-lol') == 'yay') // false
```
(https://codepen.io/spenser/pen/NWKaqva)


In theory, just passing in the param value to the `.setAttribute` would just work in `set_data.ts`, but I'm sure there's a reason stringify exists [here](https://github.com/kenwheeler/cash/blob/612635aae630afe967569799607f5063bc290e8d/src/data/helpers/set_data.ts#L7)?

Mad respect for this project and the paranoia around bundle size ✊

**Comment by fabiospampinato** [comment]
> In theory, just passing in the param value to the .setAttribute would just work in set_data.ts, but I'm sure there's a reason stringify exists here?

Yes, calling `$0.setAttribute ( 'foo', {} )` gives you `data-foo="[object Object]"` which is not what you want.

**Comment by bananatron** [comment]
Ahh yes ok, but I wouldn't expect that passing an object into data would work anyway (since data-attributes in the DOM wouldn't support it w/out (de)serialization).

Then, I discovered that jquery [doesn't even manipulate the DOM](https://stackoverflow.com/questions/13524107/how-to-set-data-attributes-in-html-elements) with data attributes when you use `.data()`, so my expectations were wrong (you can pass like anything in).

Via [jquery documentation](https://api.jquery.com/data/):
```Using the data() method to update data does not affect attributes in the DOM. To set a data-* attribute value, use attr.```

Although this 'virtual data' prevents improper serialization and allows a wider range of objects being attached to a 'data' attribute, it forces you to use jquery to continue operations on this object, and doesn't reflect the changes in the DOM (which seems strange/bad, imo). I'm wondering if this was a holdover from a time before data attributes were widely adopted?

It also would seem to me that there's no way to know what your intention is if you're passing an object into `.data` as the second argument and the library should should reject it, however that would not be in parody w/ jquery either. The current implementation also doesn't have strict parody and has (imo) unintended consequences with the current form of DOM manipulation so it seems like a tough call.


🤷‍♂ 🤷‍♀ 🤷‍♂ 🤷‍♀ 🤷‍♂ 🤷‍♀ 🤷‍♂ 🤷‍♀ 🤷‍♂ 🤷‍♀ 😂 

Let me know if I can help at all.

**Comment by fabiospampinato** [comment]
On a second thought I'm closing this as I don't think there's actually anything to fix.

> ### Expected behavior
> 
> ```js
> $('#lol').data('whoah', 'yeah')
> // <div id="lol" data-whoah="yeah"></div>
> ```

That's not what jQuery does actually.

> I'm wondering if this was a holdover from a time before data attributes were widely adopted?

Dunno, I think they are caching values on DOM nodes for performance (no serialization/deserialization cost) and for allowing any kind of values to be saved this way (functions etc. aren't JSON-serializable).

But I don't think the serialization/deserialization cost is actually meaningful as in pretty much all scenarios one wouldn't constantly read and write those attributes, nor it's useful in practice to be able to attach functions, regexes etc.

On the other hand what jQuery's approach break is compatibility with libraries like React, which IMHO is a more important issue. Also our implementation allows for smaller bundles.

I've updated the [migration guide](https://github.com/kenwheeler/cash/blob/master/docs/migration_guide.md#data-caching), explaining better the differences in `$.fn.data` between Cash and jQuery.
