### ISSUE TITLE
exception thrown when getValue is run against an input type=file with the multiple attribute

### ISSUE THREAD

**Issue by stefanwright** [kenwheeler/cash#299]
When passing an input with the type of file through to function getValue(ele) if it contains the multiple attribute then it tried to then run ele.options.selectedIndex but fails because options is undefined. It would seem this function only accounted for multiple being used on <select>'s

The fix I implemented myself was to change the if statement to if(ele.multiple && ele.options && ele.options.selectedIndex !== -1) and this stops the exception being thrown.

**Comment by fabiospampinato** [comment]
I'll fix this soon, although running `$.fn.value` on a file input is a bit meaningless I think, as the `.value` property will always point to a single fake path, what you probably want is to retrieve some information about all files, for that you need to access the `.files` property instead.

**Comment by fabiospampinato** [comment]
Fixed in v4.1.5.
