### ISSUE TITLE
outerWidth returns 0 for hidden objects

### ISSUE THREAD

**Issue by FredHappyface** [kenwheeler/cash#300]
### Preamble 

Not sure if this is a bug or to fall inline with vanilla JS. I'd assume so if this is supposed to be compatible with JQuery 

### Current behavior

$(element).outerWidth(true); returns 0 when the element is hidden 

### Expected behavior

$(element).outerWidth(true); returns the same width as when the element is shown

**Comment by fabiospampinato** [comment]
This is mentioned in the migration guide: https://github.com/kenwheeler/cash/blob/master/docs/migration_guide.md#widthheight-of-hidden-element
