### ISSUE TITLE
Event element not defined

### ISSUE THREAD

**Issue by tonxxd** [kenwheeler/cash#301]
### Current behavior
When listen to events on a element the element is not definet in the handler
$("body").on("click", ".dropdown", (e) => {
    console.log($(this)) . --> Cash {}
})
So i can not use methods on the element such addClass etc...

I am using cash with parcel js (https://parceljs.org) and importing it like
import $ from 'cash-dom'

Thank you

**Comment by fabiospampinato** [comment]
That's not how arrow functions work, you should look that up.

**Comment by tonxxd** [comment]
Ah yes sorry, my fault!
