### ISSUE TITLE
Reducing size.

### ISSUE THREAD

**Issue by aleph1** [kenwheeler/cash#302]
In the minified version of cash there are numerous instances of functions being assigned to y.prototype in order to build the function chain. Since extend is available I sifted through the minified version and extended y.prototype by effectively calling extend (F) on the prototype:

~~~~
F( y.prototype,{
  splice: ba,
  get: function(a) {
    return void 0 === a ? u.call(this) : this[0 > a ? a + this.length : a]
  },
  etc.
} );
~~~~

This saves almost 150 bytes off of the minified gzipped version. However, I am not familiar with typescript, and unsure if it would be possible to use extend as part of the build process versus each function being assigned using Cash.prototype.* = function. I tested the modified version using Qunit and it passes all tests as expected.
[cash.min.txt](https://github.com/kenwheeler/cash/files/3714883/cash.min.txt)

**Comment by fabiospampinato** [comment]
I don't think you're running this experiment correctly.

- Those prototype assignments will get mostly compressed away by gzip, so they are not much of an issue.
- Assigning to the prototype directly should be faster.
- Not using extend directly allows partial builds to strip it out safely.
- You can't call extend a single time with all those methods, as those methods have each their own file in the repository, and we can't switch to a monolithic approach without rewriting the partial compilation pipeline too (which I have no interest in doing).

**Comment by aleph1** [comment]
Thanks! It does save 150 bytes on the gzipped version, but it would definitely require a rewrite that would make it less flexible :( Great library!

**Comment by fabiospampinato** [comment]
If you can find other potential ways to squeeze bytes out of the bundle I'm all ears 👍
