### ISSUE TITLE
Is there an elegant way to use cash-dom in Node without browser

### ISSUE THREAD

**Issue by patarapolw** [kenwheeler/cash#304]
Currently, I have to use `async init()`.

```typescript
import { Cash, CashStatic, Selector } from "cash-dom";

let $: (((selector?: Selector, context?: Element | HTMLElement | Document | Cash) => Cash) & CashStatic) | null = null;

class RevealMd {
  async init() {
    if (!this.isBrowser) {
      const { JSDOM } = await import("jsdom");

      this._dom = new JSDOM(h("html", [
        h("head", [
          h("meta", { charset: "utf-8" })
        ]),
        h("body", [
          h(".reveal", [
            h(".slides")
          ])
        ])
      ]).outerHTML);
      (global as any).window = this.window;
      (global as any).document = this.window.document;
    }

    this.window.revealMd = this;

    $ = (await import("cash-dom")).default;
  }
}
```

Otherwise, `cash-dom` will complain that `document is not defined.` , so importing `import $ as "cash-dom"` on the very top is not an option.

Also, is it possible to use no JSDOM at all?, like Cheerio. (Note that I couldn't use `$: CheerioStatic | CashStatic` as well.)

**Comment by fabiospampinato** [comment]
@patarapolw You should probably do: `import 'jsdom-global/register'` instead, check out [jsdom-global](https://github.com/rstacruz/jsdom-global).

> Also, is it possible to use no JSDOM at all?, like Cheerio. (Note that I couldn't use $: CheerioStatic | CashStatic as well.)

Cash expects to be executed in a context where DOM globals are available, you may use something other than JSDOM probably but it needs something.

**Comment by patarapolw** [comment]
Thanks, but I reality, I tried to dual Browser/Node module, so I have to,

```typescript
// jsdom-register.ts
export const isNode = (typeof module !== "undefined" && module.exports);

if (isNode) {
  require("jsdom-global")();
}
```

```typescript
// index.ts
import { isNode } from "./jsdom-register";
import $ from "cash-dom";
```

**Comment by fabiospampinato** [comment]
That's not too bad. I don't understand why `./jsdom-register` is exporting `isNode` though. Just loading your `jsdom-register` module at the entrypoint of your bundles would suffice.

**Comment by patarapolw** [comment]
I just need isNode later on.
