### ISSUE TITLE
Errors in Node

### ISSUE THREAD

**Issue by arpowers** [kenwheeler/cash#305]
### Feature description

Enable Cash to be included in Node without errors. 

### Feature motivation

For SSR apps, its convenient to not make special accommodations for libs that are meant to run only in the client. 

In our case, this library errors in Node on inclusion. Ideally we could include it, but not run it. This allows us to use the same utility module for both envs. 

```js
// just don't assume we have document element 
if(!document) return
```

what is happening now: 
<img width="609" alt="Screen Shot 2019-10-28 at 1 54 23 PM" src="https://user-images.githubusercontent.com/308134/67712907-7a0d3600-f98a-11e9-8665-f0ebe87aafe3.png">

Is this feature present in jQuery? Yes

**Comment by fabiospampinato** [comment]
I don't see this happening but if somebody would like to submit a PR about this we can talk about it.

For now just use [null-loader](https://github.com/webpack-contrib/null-loader) in your server-side bundles or lazy load Cash conditionally so that you can detect if you're in a browser environment.

**Comment by arpowers** [comment]
@fabiospampinato it really would be trivial to put a flag in here to detect when this is loaded in node and bail.  Adding this to null loader and/or lazy loading it are expensive in terms of complicating your code base. 

As far as a pull request, `document` and `window` are currently being assumed in the first functional line of the plugin. Therefore, there might be more architectural issues since i can't just do: 

```js
// bail if in node
if(!document) return 
```
can you reopen this?

**Comment by fabiospampinato** [comment]
I'd be happy to review a PR that addresses this, I'm not sure the fix is as simple as you may think.

**Comment by limonte** [comment]
Here's how this check is implemented in sweetalert2: https://github.com/sweetalert2/sweetalert2/search?q=isNodeEnv&unscoped_q=isNodeEnv

**Comment by katerlouis** [comment]
6+ years later, and I still would like to use this library in Nuxt SSR without it breaking :'(
