### ISSUE TITLE
Prepend inserts HTML snippet elements in different order than jQuery.

### ISSUE THREAD

**Issue by aleph1** [kenwheeler/cash#308]
Calling prepend with an HTML snippet with multiple siblings results in insertion in the opposite order of jQuery (see: https://jsfiddle.net/br1qctwp/).

**Code:** $( 'body' ).prepend( '&lt;p&gt;1st paragraph&lt;/p&gt;&lt;p&gt;2nd paragraph&lt;/p&gt;' );

**Result:**
2nd paragraph
1st paragraph

**Expected result:**
1st paragraph
2nd paragraph

**Comment by aleph1** [comment]
The opposite result of jQuery also occurs if .prepend is called with multiple arguments: $( 'body' ).prepend( '&lt;p&gt;1st paragraph&lt;/p&gt;','&lt;p&gt;2nd paragraph&lt;/p&gt;' );

**Comment by aleph1** [comment]
I took a quick look at fixing this, but I think it will be necessary to refactor code to resemble jQuery's domManip function (https://github.com/jquery/jquery/blob/master/src/manipulation.js#L96). I modified prepend and insertContent to work as expected, but if the parent argument passed to insertContent is a collection of more than one item it breaks.

Refactoring might require merging some of the manipulation functions into a single typescript file, but I am not sure if this would break cash’s modular approach to code.

**Comment by fabiospampinato** [comment]
@aleph1 I think we would just need to reverse the elements array/collection, no?

**Comment by aleph1** [comment]
Yes, it requires applying reverse to the arguments passed to prepend as well as the selector generated in the loop:

~~~
Cash.prototype.prepend = function () {
  var _this = this;

  each(reverse.apply(arguments), function (i, selector) {
    insertContent(_this, reverse.apply(cash(selector)


), true);
  });
  return this;
}; 
~~~

The complex test case for jQuery is here: https://jsfiddle.net/51ts0d4m/1/
The modified cash.js and complex test are attached. I can put in a pull request for this.
[cash-prepend-test.zip](https://github.com/kenwheeler/cash/files/3902895/cash-prepend-test.zip)

**Comment by aleph1** [comment]
#309

**Comment by aleph1** [comment]
Is there anything else I can contribute in terms of this commit? https://github.com/kenwheeler/cash/pull/309

**Comment by limonte** [comment]
@aleph1 adding a simple test case would be nice
