### ISSUE TITLE
Sorting of namespaces in `parseEventName`

### ISSUE THREAD

**Issue by PetarMax** [kenwheeler/cash#310]
In the `parseEventName` function in the `parse_event_name.ts` file, the obtained namespaces are sorted. 

Could you please tell me what the reason for that is?

**Comment by fabiospampinato** [comment]
I don't quite remember why, looking at the codebase it doesn't seem like there's any use for that now, I'll take a closer look at it later and see if we can safely stop doing the sorting.

**Comment by PetarMax** [comment]
Thanks for the reply - it seems that jQuery is doing a similar thing, but the why still remains.

The reason I'm asking in the first place is that I'm part of a project on analysing JavaScript/DOM at Imperial College; we're trying to symbolically test parts of your library and that sorting is just killing us.

**Comment by fabiospampinato** [comment]
@PetarMax I'm not familiar with symbolic testing, why is that sorting getting in your way? 🤔 And could you tell me a little about the purpose of your research? Maybe I can help in some way.

**Comment by PetarMax** [comment]
We have a tool, called JaVerT, that can do several types of program analysis on JavaScript code (https://vtss.doc.ic.ac.uk/publications/FragosoSantos2019JaVerT.html). We are currently extending JaVerT to support reasoning about DOM events and we are trying to evaluate this extension on some real-world code. In particular, we are trying to symbolically test the events module of cash, with the first goal being 100% line coverage.

The analysis that we are using is called whole-program symbolic testing, where the user writes assumptions and assertions about the inputs and outputs of their functions using symbolic number/strings/etc. This type of testing is much more comprehensive than concrete testing - for example, with a single test, we can guarantee that the `on` function behaves correctly for ALL strings of length not greater than a given bound. This is not feasible with standard, concrete testing.

The reason we're having problems with sorting is that it requires of us to reason automatically  about arbitrary string comparison, which is very difficult. For example, if you represent an event type with a symbolic string `e`, and then do sth like `ele.on (e, handler)` followed by an `ele.trigger(e)`, JaVerT has to analyse all possible forms `e` can take - it may or may not have spaces or dots (to separate namespaces), and if it has namespaces, then it would have to sort them symbolically. At the moment, we can't do that.

Since you know the library very well, perhaps you could help us in the following: we believe that the events-related functions that we should be targeting are, essentially, the ones in the events folder - are there perhaps any other ones on which they heavily depend that we should also be looking at?

**Comment by fabiospampinato** [comment]
@PetarMax Interesting, it sounds to me a bit like type checking if that makes sense 🤔.

I haven't removed the sorting yet, as I'll have to take a closer look at the codebase first to understand if that is actually useful. For your intents I guess though you could just fork the library and remove the `sort` call.

Everything strictly related to events is defined in the `src/events` folder and nowhere else, but those files may also depend on some other general utilities, all those `// @require [path]` comments you see indicate to our bundler that the file at `[path]` is a dependency and should be loaded first.

I don't know if that's useful but running `npm run graph` will generate a dependency graph for you, I'm attaching one below. Yellow nodes are root nodes. Also you could pretty easily just start deleting the files that you don't need, rebundle the library with `npm run build:deploy`, and get a more manageable codebase. If the bundler finds any issues (like a missing dependency) it will tell you.

[graph.svg.zip](https://github.com/kenwheeler/cash/files/3963357/graph.svg.zip)

**Comment by PetarMax** [comment]
Excellent, thanks, that could be of help. For the moment, we have the sorting commented out.

Type checking is a form of static analysis, just like symbolic execution, with symbolic execution being more complex. For example, see one of our symbolic tests below. It uses some analysis-related constructs, such as `symb_string` to create a symbolic string, and `Assume` and `Assert`to guide the analysis.

[01_main.js.zip](https://github.com/kenwheeler/cash/files/3963583/01_main.js.zip)

**Comment by fabiospampinato** [comment]
I've taken a closer look at this and sorting the namespaces is required in order to ensure that the order of namespaces doesn't matter. Basically we are attaching back the provided namespaces to triggered events, [here](https://github.com/kenwheeler/cash/blob/master/src/events/trigger.ts/#L22), and without sorting those namespaces first the resulting `event.namespace` property might get set to different strings depending in which order the namespaces have been provided, which may lead to subtle bugs. Basically without sorting [this test](https://github.com/kenwheeler/cash/blob/master/test/modules/events.js/#L140-L161) will fail.

**Comment by PetarMax** [comment]
Understood. I'm still finding this to be an arbitrary decision, likely first made by jQuery and then inherited by cash. In fact, I think it's more likely for subtle bugs to be introduced when developers add namespaces like `foo.bar` and then attempt to reason about `event.namespace` and get `bar.foo` instead from the framework.

**Comment by fabiospampinato** [comment]
> Understood. I'm still finding this to be an arbitrary decision, likely first made by jQuery and then inherited by cash.

Yeah personally I've never used `event.namespace` 🤷‍♂.

> In fact, I think it's more likely for subtle bugs to be introduced when developers add namespaces like foo.bar and then attempt to reason about event.namespace and get bar.foo instead from the framework.

Maybe, but it'd be weird if the order of namespaces didn't matter when attaching/detaching events but mattered when setting `event.namespace` I think.

**Comment by PetarMax** [comment]
> Maybe, but it'd be weird if the order of namespaces didn't matter when attaching/detaching events but mattered when setting `event.namespace` I think.

True.
