### ISSUE TITLE
RFC: Dropping support for IE10

### ISSUE THREAD

**Issue by fabiospampinato** [kenwheeler/cash#315]
I'm thinking of dropping support for IE10, according to [Can I Use](https://caniuse.com/usage-table) IE10 usage worldwide dropped to 0.03%. By dropping support for it we can simplify a few methods and potentially make them slightly faster.

Thoughts?

**Comment by fabiospampinato** [comment]
Also I just recently managed to squeeze the minified and gzipped version of our bundle down to 5010 bytes, but I don't see any non crazy ways to squeeze 11 more bytes out and bring the library's size back below 5000 bytes, dropping support for IE10 will surely help achieve this silly goal.

**Comment by limonte** [comment]
Yes. IE10 is dead.

Keep in mind that this change would require a new major release (i.e. it's breaking)

**Comment by fabiospampinato** [comment]
IE10 is no longer supported: https://github.com/kenwheeler/cash/commit/a58e5799019e0b911ea830a64de78f26391a568e
