### ISSUE TITLE
Add `toArray()`

### ISSUE THREAD

**Issue by benface** [kenwheeler/cash#319]
### Feature description

Retrieve all the elements contained in the set, as an array.

```
$('li').toArray()
```

### Feature motivation

I would like to be able to sort items in a collection, with `Array.prototype.sort`:

```
$('.list li').toArray().sort(function(a,b) {
     return a.dataset.kid > b.dataset.kid ? 1 : -1;
}).appendTo('.list');
```

Is this feature present in jQuery? Yes: https://api.jquery.com/toArray/

Thank you!

**Comment by fabiospampinato** [comment]
Just use `$.fn.get` instead.

You can write `$.fn.toArray = $.fn.get` in your code if you wish.
