### ISSUE TITLE
prepend() (and I guess other methods?) is broken in v5

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#320]
@fabiospampinato apparently there's a big room for improving code coverage because this issue is trivial and absolutely should be covered by a simple test case.

### Current behavior

```js
const cashElement = $('<div>world</div>')
cashElement.prepend('<span>hello, </span>')
```

### Expected behavior

```html
<span>hello, </span>world
```

### Actual behavior

```html
world<span>hello, </span>
```

Live demo: https://jsfiddle.net/v7g5oe3j/1/

**Comment by fabiospampinato** [comment]
There is a test about `prepend`, I think the issue here might be that `world` is a text node and not an element node 🤔.

I'll make sure to fix this, and I also should spend some time running jQuery's test suite with cash, that way you really can catch a lot of errors/differences.
