### ISSUE TITLE
Setup code coverage

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#321]
### Feature description

If the software is not covered by tests, it's broken. In order to see how well `cash` is covered by tests, code coverage should be set up.

This request is not about "100% code coverage". It is about "how well is cash covered by test". Me and folks out there would like to see a number. Is it 10%? 50%? 80%?

It should be relatively easy to set up code coverage reporting with karma: https://github.com/karma-runner/karma-coverage

### Feature motivation

Trivial things are getting broken: https://github.com/kenwheeler/cash/issues/320 There should be a representation of which methods are covered by tests and which aren't.

---

I personally use coveralls.io and I can recommend it for usage.

**Comment by fabiospampinato** [comment]
> There should be a representation of which methods are covered by tests and which aren't.

All methods should have at least a test associated with them I think.

PR welcome for getting some coverage reports.

**Comment by fabiospampinato** [comment]
I think a more useful feature would be to be able to run Cash's test suite with jQuery.

**Comment by limonte** [comment]
> > There should be a representation of which methods are covered by tests and which aren't.
> 
> All methods should have at least a test associated with them I think.
> 
> PR welcome for getting some coverage reports.

PR is coming :rocket: 

The code coverage is 96.33% which is great!

**Comment by fabiospampinato** [comment]
> I think a more useful feature would be to be able to run Cash's test suite with jQuery.

Done.

**Comment by limonte** [comment]
Amazing! I know that you don't like badges in README, but this one would be good to have:

[![Coverage Status](https://coveralls.io/repos/github/kenwheeler/cash/badge.svg?branch=master)](https://coveralls.io/github/kenwheeler/cash?branch=master)

For some people (including myself) that would be one of the signs of a properly made software which is safe to use in production.

**Comment by fabiospampinato** [comment]
> For some people (including myself) that would be one of the signs of a properly made software which is safe to use in production.

🤔 Yeah but I prefer to keep the readme cleaner. Also I don't really think there are many users we could swing over to Cash just by adding badges.

Ps. we are at ~100% now.

**Comment by fabiospampinato** [comment]
> I think a more useful feature would be to be able to run Cash's test suite with jQuery.

I'm finding quite a few bugs this way 🤔
