### ISSUE TITLE
jQuery's test suite reports

### ISSUE THREAD

**Issue by fabiospampinato** [kenwheeler/cash#323]
I'm going to use this issue for keeping track of a few stats about jQuery's test suite, that we can run with a patched version of jQuery that uses Cash's methods, mostly about how many tests we are passing for each module.

**Comment by fabiospampinato** [comment]
These tests should be disabled because they fail too hard, navigating the tab out to another page:

- Deprecated:
 - `trigger() shortcuts`
- Event:
  - `on/off(Object), on/off(Object, String)`
  - `on immediate propagation`
  - `originalEvent type of simulated event`
- Manipulation:
  - `remove() event cleaning `
  - `detach() event cleaning `
- Selector:
  - `Iframe dispatch should not affect jQuery (#13936)`

These other tests are too slow, mostly because we aren't running the test suite properly and the mock server for dealing with AJAX request isn't started:


- Manipulation:
  - `Check if CSP nonce is preserved`
  - `Check if CSP nonce is preserved for external scripts with src attribute`
  - `jQuery.globalEval supports nonce`
- Event:
  - `on(beforeunload)`
  - `preventDefault() on focusin does not throw exception`
  - `focusout/focusin support`
  - `focus-blur order (#12868)`
  - `Event handling works with multiple async focus events (gh-4350)`
- AJAX:
  - `jQuery.ajax() - execute js for crossOrigin when dataType option is provided`
  - `jQuery.ajax() - JSONP - Query String (?n)`
  - `jQuery.ajax() - JSONP - Explicit callback param`
  - `jQuery.ajax() - JSONP - Callback in data`
  - `jQuery.ajax() - JSONP - POST`
  - `jQuery.ajax() - JSONP`
  - `jQuery.ajax() - JSON by content-type disabled with options`
  - `jQuery.ajax() - transitive conversions`
  - `#8205 - jQuery.ajax() - JSONP - re-use callbacks name`
  - `#11426 - jQuery.ajax() - loading binary data shouldn't throw an exception in IE`
  - `gh-2587 .*`
  - `jQuery.ajaxSetup({ timeout: Number }) - with global timeout`
  - `jQuery.fn.load() - 404 error callbacks`
  - `#2046 - jQuery.fn.load( String, Function ) with ajaxSetup on dataType json`
  - `#10524 - jQuery.fn.load() - data specified in ajaxSettings is merged in`
  - `jQuery.ajax() - responseText on error`
  - `jQuery.ajax() - events with context`
- Offset:
  - `empty set`

**Comment by fabiospampinato** [comment]
This is how many tests we are passing right now:

- ready: 12/19
- basic: 52/57
- core: 324/373
- callbacks: 1297/1297
- deferred: 492/492
- deprecated: 40/46
- support: 5/10
- data: 320/376
- queue: 46/47
- attributes: 384/525
- event: 221/412
  - inspect more throughly
- selector: 533/604
- traversing: 214/286
- manipulation: 543/731
- wrap: 50/74
- css: 520/688
- serialize: 30/35
- ajax: 397/444
- effects: 570/669
- offset: 136/808
- dimensions: 56/164
- animation: 64/64
- tween: 70/70
- total: 5094/6781

I think I discovered quite a few (mostly very minor) bugs this way.

Many of the failing tests come from methods we either don't implement at all or not fully, meaning we don't support all possible ways to pass arguments to all methods as jQuery does.

The remaining failing tests are mostly about edge cases.

I'll try to fix some of them and align Cash more with jQuery, at the moment I have a 910 lines document containing tests coming from jQuery's test suite that we I should take a closer look at.

**Comment by limonte** [comment]
Great stuff, thank you @fabiospampinato for making `cash` great!

**Comment by fabiospampinato** [comment]
As of today these other tests should be disabled for performance:

- Core:
  - `jQuery.readyException (custom)`

And these many tests are passing:

- ready: 12/19
- basic: 53/57 (+1)
- core: 327/372 (+3)
- callbacks: 1297/1297
- deferred: 492/492
- deprecated: 40/46
- support: 5/10
- data: 323/376 (+3)
- queue: 46/47
- attributes: 405/525 (+21)
- event: 210/412 (-11 (?))
- selector: 548/604 (+15)
- traversing: 226/286  (+12)
- manipulation: 552/731 (+9)
- wrap: 55/74 (+5)
- css: 527/688 (+7)
- serialize: 30/35
- ajax: 397/444
- effects: 579/669 (+9)
- offset: 118/808 (-18 (?))
- dimensions: 56/164
- animation: 64/64
- tween: 70/70
- total: 5158/6781 (+64)

I'm not sure what's the deal with the regressions there, I'll have to take a second look at them, and it's impossible to get anywhere near 100% tests passing, but I'd say generally the more tests we can make pass the better, even though most of the bugs I'm fixing are about edge cases, a few are nice findings though.

I'm also attaching the document listing things that needs to be attentioned, I've deleted two thirds of it so far, still a fair amount of stuff left.

[BUGS.md.zip](https://github.com/kenwheeler/cash/files/4011641/BUGS.md.zip)

**Comment by fabiospampinato** [comment]
Updated report:

- ready: 12/19
- basic: 63/65 (+10)
- core: 324/372 (-3)
- callbacks: 1297/1297
- deferred: 492/492
- deprecated: 44/48 (+4)
- support: 5/10
- data: 323/376
- queue: 46/47
- attributes: 413/531 (+8)
- event: 241/418 (+31)
- selector: 548/604
- traversing: 255/317 (+29)
- manipulation: 552/731
- wrap: 55/74
- css: 527/688
- serialize: 34/35 (+4)
- ajax: 397/444
- effects: 579/669
- offset: 118/808
- dimensions: 56/164
- animation: 64/64
- tween: 70/70
- total: 5158/6823 (+74)

There's still quite a bit of work to do though, I might defer that to a later point in time.

**Comment by fabiospampinato** [comment]
Other tests to disable:

- Dimensions:
  - `window vs. large document`
- Offset:
  - `absolute`

Updated report:

- ready: 12/19
- basic: 63/65
- core: 327/372 (+3)
- callbacks: 1297/1297
- deferred: 492/492
- deprecated: 44/48
- support: 5/10
- data: 322/376 (-1)
- queue: 46/47
- attributes: 462/577 (+49)
- event: 228/350 (-13 (??))
- selector: 548/605
- traversing: 257/317 (+2)
- manipulation: 558/735 (+6)
- wrap: 53/74 (-2)
- css: 527/686
- serialize: 34/35
- ajax: 397/444
- effects: 579/667
- offset: 639/767 (+521)
- dimensions: 85/186 (+29)
- animation: 64/64
- tween: 70/70

Now for whatever reason running all tests at once creates some extra weird exceptions, possibly because of the way we are patching jQuery with Cash's methods to run this test suite, so I'm going to stop reporting the "total" section in the report.

To summarize, as I think this is pretty much the last thorough iteration I'm gonna do on this, at least for a while: some new features have been implemented, the `$.fn.offset|offsetParent|position` methods are way more aligned with jQuery now (it seems they were kind of broken before), a few important bugs have been fixed, many nuances/edge cases are now fixed/Cash is more aligned with jQuery.

The leftover failing tests are: tests about features we don't implement, tests about features we implement slightly differently (documented in the migration guide), other things jQuery smooths over which I don't think it would necessarily make sense for Cash to smooth over too, possibly other actual bugs I missed.

I'm going to quickly review the remaining failing tests for the last time now, mostly in order to update the migration guide.

Unfortunately Cash's minified and gzipped size ballooned by about ~11.2% (~600B), which is kind of lot, but I think the improvement brought to the library are worth it. I'd say now Cash is considerably more stable and reliable than it was before.

**Comment by limonte** [comment]
Outstanding work :muscle: :muscle: :muscle: 

@fabiospampinato any estimation when a release with all those fixes will be published?

**Comment by fabiospampinato** [comment]
I'd hope today.

**Comment by fabiospampinato** [comment]
"Final" report as of v6.0.1:

- ready: 12/19
- basic: 63/65
- core: 327/372
- callbacks: 1297/1297
- deferred: 492/492
- deprecated: 44/48
- support: 5/10
- data: 323/376 (+1)
- queue: 46/47
- attributes: 463/577 (+1)
- event: 244/416 (+16)
- selector: 548/605
- traversing: 259/317 (+2)
- manipulation: 561/735 (+3)
- wrap: 55/74 (+2)
- css: 527/686
- serialize: 34/35
- ajax: 397/444
- effects: 579/667
- offset: 639/767
- dimensions: 85/186
- animation: 64/64
- tween: 70/70
