### ISSUE TITLE
Errors not triggered when using document ready callback

### ISSUE THREAD

**Issue by jbjanot** [kenwheeler/cash#327]
Hi, and thanks for this great tool!

Here is a super reduced test to reproduce what I am experiencing:

```
$(() => {
    console.log(undefinedvariable);
});
```
What should be expected is an error in the console like that:
`Uncaught ReferenceError: undefinedvariable is not defined`

Instead, when running this code, the error is not shown in the console at all. I can therefore not debug my project.
In a real world example, I call an initialisation method from this callback, so any  error happening in a code called after this callback will not be shown either.

I think this might be related to this commit : https://github.com/kenwheeler/cash/commit/0670f9aa71873699192d8893cc5e8249e06e0b8d

Thank you for your help!

**Comment by fabiospampinato** [comment]
This is a corner of the library that needs improvement.

The issue with triggering errors there is that they can bring down the app basically if the callback is executed synchronously.

jQuery catches those errors automatically too.

If errors are caught automatically how do you know when there's an error though? jQuery provides `$.readyException` just for this, we currently don't.

I agree that you should at least know there's an error in the console.

The options are:

1. We revert the commits that changed this, still executing the callback synchronously sometimes, with the chance that an exception thrown from there could basically break the app.
2. We revert the commits that changed this, executing the callback always asynchronously, so if an exception happens the rest of the app can kind of ignore it.
3. We implement `$.readyException` too.

I'm not sure what the best option here is, perhaps we should align with jQuery and implement `#3` 🤔 Thoughts?

**Comment by jbjanot** [comment]
Thank you for the detailed feedback.

To be honest, I do not really understand the differences in this case between a synchronous and asynchronous function regarding the errors.
The way I use it, I always need the errors to be shown, so I would personally go with one of the first two options, as the previous versions worked for me.
I don't care that the app breaks due to an error, as I will immediately correct it and make sure it won't happen when my code goes live.
Also, I never had to use `$.readyException` when using jQuery before.

Thank you for your help!

**Comment by fabiospampinato** [comment]
> I don't care that the app breaks due to an error, as I will immediately correct it and make sure it won't happen when my code goes live.

That's a likely possibility but there's also the chance that one writes a function in there that only breaks in production, or rarely, and it would be hard to catch that.

I'll have a think about this and I'll see how's best to proceed.

**Comment by OktarinTentakel** [comment]
I'm with jbjanot in this case.

Just stumbled across this and this is a deal breaker and definitely not present in jQuery. Catching exceptions inside callbacks is my own responsibility as a dev and should not implicitly be done by a framework, especially if there is no way to access any thrown exceptions manually.

This behaviour is normally only done by Promises and they at least offer .fail()

The problem with this is, that if you are initializing frontend components generally on dom ready since before that, there's nothing there to be initialized, you'll effectively never see any error output at all, since all code runs inside the callback.

Cash may well catch its own exceptions and handle them accordingly, but should never ever catch custom code exceptions. That's the developers task.

**Comment by OktarinTentakel** [comment]
I'm guessing the attempt here is not the best of ideas:

https://github.com/kenwheeler/cash/commit/95a9e7a44441c7be4b0634bd357f1e30ae8c8e60#diff-e4a3ad86eacf2271dae63777a7feebb3

**Comment by OktarinTentakel** [comment]
Workaround until this is solved:

```
$(() => {
	try {
		foo.bar();
	} catch(ex){
		console.error(ex);
	}
});
```

This way, we'll at least get a structured error message in the dev console.

**Comment by fabiospampinato** [comment]
Fixed.

**Comment by OktarinTentakel** [comment]
@fabiospampinato thanks a lot!
