### ISSUE TITLE
drag/drop/resize support ?

### ISSUE THREAD

**Issue by adumesny** [kenwheeler/cash#332]
### Feature description
How much work would it be to add jquery-ui like drag&drop as an optional module to this ?
I see you have another JS module `svelto` which has draggable and droppable (I don't see resizable) that's JS code and doesn't appear to depend on jquery/jquery-ui, and would be great to add a TS version to this code.

### Feature motivation

The couple projects I worked with are using $ for dom manipulation (your lib would help most calls) but also do drag/drop/resize so include the bare minimal jquery-ui widgetset to do that, but still quite large.

I'm also the maintainer of gridstack and trying to remove jq/jqui and converting to typescript/html5

Is this feature present in jQuery? Yes (jqui common part actually)

**Comment by fabiospampinato** [comment]
This is out of scope, Cash is not made to be replacement for jQuery UI.

You can implement those primitives on top of Cash pretty much like you would on top of jQuery. My implementations of draggable and droppable work with Cash, and are here:

- Draggable: https://github.com/svelto/svelto/tree/master/src/widgets/draggable
- Droppable: https://github.com/svelto/svelto/tree/master/src/widgets/droppable

I haven't implemented resizable.

However they would need to be refactored as they depend on other core components of Svelto.

Unfortunately I don't have a TS version of that code or a more easily embeddable version. If you'll make one let me know and I'll be happy to link to it in the readme if it works well enough and is small enough 👍
