### ISSUE TITLE
kenwheeler.github.io web font protocol relative

### ISSUE THREAD

**Issue by Aaron-P** [kenwheeler/cash#39]
The documentation at kenwheeler.github.io uses a Google font at http://fonts.googleapis.com/css?family=Montserrat which is blocked if visiting via https, it should probably be made protocol relative.

**Comment by shshaw** [comment]
[Protocol relative URLs are now an anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/). Since HTTPS is available for Google Fonts, go ahead and use that and it will work on secure & insecure requests.

**Comment by simeydotme** [comment]
I think the docu page is gone in favour of a living README...

**Comment by shshaw** [comment]
We do need to consider updating http://kenwheeler.github.io/cash/ Perhaps just simplifying it to point people to the GitHub page for the documentation & updated info.

Doesn't look like that's a gh-pages branch in this repo, so @kenwheeler may need to provide some guidance there.

**Comment by kenwheeler** [comment]
Would be nice to have the .io site get generated from JSDoc.

**Comment by shshaw** [comment]
Something like [doxdox](https://github.com/neogeek/doxdox) may be the solution.
