### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by simeydotme** [kenwheeler/cash#41]
Hey @kenwheeler 

Just wondering if you'd consider a roadmap; it may help anyone considering contributing but is afraid they don't have the same vision as you. - Personally I'd like to contribute a bit more but am at a loss where to begin :smile: 

Regards, Si

**Comment by simeydotme** [comment]
not sure if these are helpful but maybe lend some insight:

http://inside.hotjar.com/support/discussions/topics/1000039114
http://stonehearth.net/roadmap/
https://trello.com/b/ChO1sGkP/roadmap
https://confluence.jetbrains.com/display/RUBYDEV/Development+Roadmap

Essentially they are all just different ways of doing "milestones" but instead of from a bug/issue point of view from a feature/improvement angle. I appreciate that would take some effort/time and maybe it's not efficient or particularly useful to do it; I know what it's like to code with the flow, or dev by the seat of your pants :stuck_out_tongue: 

I reckon there's some smart people ready to code though, who just want a bit of direction - if you could manage a little bit of admin :briefcase: :man: - but I also appreciate maybe you want to figure it out yourself; which is completely understandable :dancer: 

by the looks of it my personal roadmap should read: "learn ES6" if the codebase will be converted to ES6 :stuck_out_tongue_closed_eyes:

**Comment by vivekimsit** [comment]
:+1:  for ES6
