### ISSUE TITLE
add toggleClass()

### ISSUE THREAD

**Issue by puro** [kenwheeler/cash#46]
I dont mean to bloat the module, but toggleClass is widely used.

    toggleClass: function (className) {
      var classes = className.match(notWhiteMatch), l, newClassName;

      this.each(function (v) {
        l = classes.length;
          while (l--) {
            v.classList.toggle(classes[l]);
          }
      });

      return this;
    }

  });

**Comment by vivekimsit** [comment]
Hi, why not use the existing apis of cash?

eg:
```
  toggleClass: function(className) {
    if (this.hasClass(className))
      this.removeClass(className);
    else
      this.addClass(className);
  }
```

**Comment by simeydotme** [comment]
:+1:

**Comment by simeydotme** [comment]
```js

toggleClass: function(className) {
    return (this.hasClass(className)) ? 
      this.removeClass(className) : 
      this.addClass(className);
}

```

**Comment by puro** [comment]
You are right.

**Comment by simeydotme** [comment]
why close? haha?
