### ISSUE TITLE
CDN link is broken 

### ISSUE THREAD

**Issue by OrKoN** [kenwheeler/cash#48]
//cdn.jsdelivr.net/cash/0.0.3/cash.min.js does no work and the latest available version on jsdelivr is 0.0.2

**Comment by jimaek** [comment]
I uploaded this version and the URL should be working now

**Comment by shshaw** [comment]
Added an `update.json` pull request to JSDelivr which should help it auto-update: https://github.com/jsdelivr/jsdelivr/pull/10248

**Comment by shshaw** [comment]
JSDelivr is now showing the latest 1.1.0 release, as well as 1.0.0
https://www.jsdelivr.com/?query=cash
https://cdn.jsdelivr.net/cash/1.1.0/cash.min.js
