### ISSUE TITLE
Testing compatibility with bootstrap

### ISSUE THREAD

**Issue by IngwiePhoenix** [kenwheeler/cash#52]
I just decided to silently replace jquery.js with cash.js...very sneakily. :)

It seems to actually run down pretty far - my jQuery modules check in properly. But at some point, I see this error:

    Uncaught TypeError: this[0].getAttribute is not a function

Cause:
```javascript
        attr: function (name, value) {
          if (!value) {
       ----> return this[0].getAttribute(name);
          } else {
            this.each(function (v) {
              return v.setAttribute(name, value);
            });
    
            return this;
          }
        },
```

I followed the stack trace, and this is the line that causes the error:

    $(document).on('click.bs.alert.data-api', dismiss, Alert.prototype.close)

That seems to resolve to `bootstrap/src/js/alert.js`.

What could the issue be?

**Comment by IngwiePhoenix** [comment]
Full stacktrace:

```
Uncaught TypeError: this[0].getAttribute is not a function
    fn.extend.attr @ b69098715d71615baa6c-main.js:816
    fn.extend.data @ b69098715d71615baa6c-main.js:950
    registerEvent @ b69098715d71615baa6c-main.js:1030
    (anonymous function) @ b69098715d71615baa6c-main.js:1090
    cash.each @ b69098715d71615baa6c-main.js:733
    fn.extend.each @ b69098715d71615baa6c-main.js:885
    fn.extend.on @ b69098715d71615baa6c-main.js:1070
    (anonymous function) @ b69098715d71615baa6c-main.js:3920
    (anonymous function) @ b69098715d71615baa6c-main.js:3922
    (anonymous function) @ b69098715d71615baa6c-main.js:3924
    __webpack_require__ @ bootstrap b69098715d71615baa6c:50
    (anonymous function) @ b69098715d71615baa6c-main.js:81
    (anonymous function) @ b69098715d71615baa6c-main.js:108
    __webpack_require__ @ bootstrap b69098715d71615baa6c:50
    (anonymous function) @ b69098715d71615baa6c-main.js:17
    (anonymous function) @ b69098715d71615baa6c-main.js:68
    __webpack_require__ @ bootstrap b69098715d71615baa6c:50
    webpackJsonpCallback @ bootstrap b69098715d71615baa6c:21
    (anonymous function) @ b69098715d71615baa6c-main.js:1
```

You can see the contents of the entire file here: https://gist.github.com/IngwiePhoenix/1d9d49bb5b5e00ea3ec1

**Comment by kenwheeler** [comment]
I believe it's an issue related to getAttributes availability on window and document, working out a fix as we speak

**Comment by IngwiePhoenix** [comment]
Cool! Let me know when you have something. :)

**Comment by simeydotme** [comment]
I think this might be working, now?

**Comment by shshaw** [comment]
This should be working with 1.3.0. Let us know if you find any other incompatibilities. Thanks!

**Comment by noBlubb** [comment]
Hey,
I'm about to drop cash.js into bootstrap v4 alpha 2. Other than v3 this time they seem to use special jQuery event handlers (?) https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js#L88

Any ideas? Maybe as a plugin?

**Comment by shshaw** [comment]
Hm, it looks like they're using some very jQuery specific features. jQuery has the `$.event.special` object for mapping events that need special syntax or handling. #128 brought up where Cash may need something similar for handling `focusin/out` events in FireFox, but we haven't specifically made plans for jQuery special event compatibility.

I'd suggest adding `$.event = { special: {} }` after including jQuery but before including Bootstrap to see if that allows the transition end events to work in browsers you need to support. I'm sure there's some browser specific bug that the Bootstrap code is patching, but an event handler on `transitionend` (or the prefixed version) should work as expected.

**Comment by iantearle** [comment]
How do you get around the "Bootstrap's JavaScript requires jQuery" warning? Or just a case of ignoring it? Does anyone know if cash if fully compatible with Bootstrap 3.3.7?
