### ISSUE TITLE
Implementing a sticky footer with Cash

### ISSUE THREAD

**Issue by IngwiePhoenix** [kenwheeler/cash#53]
I was previously using a sticky-footer plugin for jQuery, but the amount of jQuery specific API it uses is big... so, I would like to know how I could implement a sticky footer with Cash?

With sticky footer, I mean that the footer always stays on the bottom.

**Comment by kenwheeler** [comment]
Couldn't this be accomplished with position fixed?

**Comment by IngwiePhoenix** [comment]
That would overlap existing content when the actual content was longer. So this one falls out of the choice...
