### ISSUE TITLE
Error in Google Chrome 44

### ISSUE THREAD

**Issue by thesbros** [kenwheeler/cash#54]
In the beta version of Google Chrome (v. 44), I get the following error when using .find():
```js
Uncaught TypeError: Cannot set property length of #<NodeList> which has only a getter
cash.extend.fn.extend @ cash.js:90
fn.extend.find @ cash.js:601
```

**Comment by thesbros** [comment]
[This](https://github.com/AdventurerGame/Adventurer/blob/21fbd1388e731c5715fea9b8531ab6b99155901c/app/scripts/classes/buildings/ActiveBuilding.js#L20) is the line of code that causes the error in my application.

**Comment by kenwheeler** [comment]
That's mighty strange. Is this only in 44 beta? How about Canary?

**Comment by thesbros** [comment]
Same happens in Canary. (v. 45)

**Comment by kenwheeler** [comment]
Ok I'll download both tomorrow and sort this out

**Comment by thesbros** [comment]
Alright, thanks. :)

**Comment by kenwheeler** [comment]
Just tested this in Canary 45 and it looks like they fixed it.
