### ISSUE TITLE
Browser Support - What does "for modern browsers" mean?

### ISSUE THREAD

**Issue by simbo** [kenwheeler/cash#55]
Not really an issue, but i wonder which browsers/devices are really supported by cash?

I guess it's like jquery 2 not supporting IE<=8.  

But can you say a clear border where full browser support starts/ends?

**Comment by kenwheeler** [comment]
> ie8

**Comment by sandstrom** [comment]
Please define it as evergreen (possibly including IE11). For legacy support everyone is better off just using jQuery.

**Comment by kenwheeler** [comment]
or I could just define it as ie9+.

**Comment by Aethelflaed** [comment]
@kenwheeler I like your response's style ! :+1:

**Comment by shshaw** [comment]
Clarified in README.MD
