### ISSUE TITLE
Passing a `null` or `undefined` delegate to `$.fn.on` is handled as a real delegate

### ISSUE THREAD

**Issue by lvanengelen** [kenwheeler/cash#56]
`$(".foo").on("click", undefined, fn)` should work the same as `$(".foo").on("click", fn)`. Libraries such as BaconJS, which call `$.fn.on` themselves do this when setting up events without a delegate.

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/cash/blob/master/src/events.js#L45
Should just need to change that line to check for undefined/null as well?

**Comment by lvanengelen** [comment]
Yup, think so.
Op 13 jun. 2015 19:42 schreef "Simon Goellner" <notifications@github.com>:

**Comment by shshaw** [comment]
This was fixed in 1.1.0.
