### ISSUE TITLE
Support for IE8

### ISSUE THREAD

**Issue by alexprice91** [kenwheeler/cash#59]
Right now addEventListener throws this error for IE8:
Object doesn't support this property or method

**Comment by simeydotme** [comment]
![screen shot 2015-06-24 at 2 12 41 pm](https://cloud.githubusercontent.com/assets/2817396/8323750/1b0712ea-1a7b-11e5-9edc-5d53ae4c03c6.png)

**Comment by Pomax** [comment]
Also note that as of January 12th 2016, Microsoft no longer supports IE8 in any official capacity. Only the latest versions of IE are supported, for each version of Windows that is still supported. As such, except for Vista SP2 only IE11 is not officially supported by Microsoft. For Vista SP2, the officially supported version is IE9, and *only* IE9.

**Comment by tiborsaas** [comment]
People shouldn't try to fix issues for IE8, it does more damage then good.

**Comment by nloveladyallen** [comment]
>Cash is a small library for **modern browsers** that provides jQuery style syntax to wrap modern Vanilla JS features.

**Comment by alexprice91** [comment]
Oh god, this comment was 9 months ago before Microsoft killed support. The only reason I would use a library instead of vanilla JavaScript is so I wouldn't need to consider cross browser oddities. Obviously that is irrelevant now.
