### ISSUE TITLE
$() should accept an existing element.

### ISSUE THREAD

**Issue by IngwiePhoenix** [kenwheeler/cash#60]
Imagine the following example:

You are using a third-party library, that returns a raw element object. Now you want to edit this using Cash - how?

```javascript
var elem = document.createElement("div");
var $e = $(elem); // Error: Can't run querySelectAll on this object.
```

How could this be made working?

**Comment by defrag** [comment]
+1 This would be very useful.

**Comment by kenwheeler** [comment]
this should absolutely work. this happens in chrome?

**Comment by defrag** [comment]
This actually works, my bad. This issue can be closed :)
