### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#61]
Before I stumbled across Cash, I tried my hand at a micro jQuery alternative ([HalfDollar.js](https://github.com/shshaw/HalfDollar.js/)). The size and feature set of Cash is almost perfect, so I don't see a point in trying to continue HalfDollar. I'd like to contribute some of those improvements to Cash, assuming this project is still active.

From my attempt, there are a few improvements that I could merge into Cash, like multiple argument `extend`, lightweight type checking (`isArray`, `isFunction`, etc), and my `init` function might be a little better. 

Another feature that might be worthwhile to add is the [smart jQuery Fallback](https://github.com/shshaw/HalfDollar.js/blob/master/src/HalfDollar.js#L49) (example on the [README](https://github.com/shshaw/HalfDollar.js/blob/master/README.md)) if the necessary methods aren't in browser (primarily `querySelectorAll`). With the fallback, `$.extend`, `$.fn.extend`, and DOM ready calls `$(function(){ ... })` will work as expected when jQuery loads.

Would you be interested in me adapting some of these and sending pull requests?

**Comment by kenwheeler** [comment]
@shshaw just seeing this now, but if you are still game I'm totally on board
