### ISSUE TITLE
$.extend - TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by hultberg** [kenwheeler/cash#62]
Hello,

I have the following DOM element selected with cash 1.0.0:
````
var baseElement = $(".editform");
````
and further down the line I need to change css on elements inside the element. Doing this with jQuery was by using `find` as I'm trying to do with cash:
````
baseElement.find(".plain").css({display: "none"});
````

When this script executes the following errors are reported:

#### Firefox
...reports the following error: `TypeError: setting a property that has only a getter` in $.extend (https://github.com/kenwheeler/cash/blob/master/src/util.js#L27)

#### Chrome
````
Uncaught TypeError: Cannot set property length of #<NodeList> which has only a getter
cash.extend.fn.extend @ cash.js:91
fn.extend.find @ cash.js:602
enableEditMode @ bidrageditor.js:17
toggleEditMode @ bidrageditor.js:12
onclick @ (index):56
````

**Comment by kenwheeler** [comment]
Does this still happen if you dont call the `css` method?
