### ISSUE TITLE
$.html() always tries to set HTML.

### ISSUE THREAD

**Issue by IngwiePhoenix** [kenwheeler/cash#63]
I just ran into an issue, where calling `$(...).html()` would set the `innerHTML` to `undefined`.
My version of Cash:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ cat bower_components/cash/bower.json | grep version
    "version": "1.0.0",
```

**Comment by IngwiePhoenix** [comment]
`if (content === "undefined") {` is improper. Add the `typeof` keyword like so:
`if (typeof content == "undefined") {`.

**Comment by kenwheeler** [comment]
Thanks!

**Comment by novns** [comment]
Still not fixed?

**Comment by fabiospampinato** [comment]
> Still not fixed?

@novns Did you check?

**Comment by novns** [comment]
> @novns Did you check?

Yes, I caught this bug myself and found this issue.

As you can see the improper comparison is not fixed as it was suggested earlier:
https://github.com/kenwheeler/cash/blob/master/dist/cash.js#L933

**Comment by fabiospampinato** [comment]
I'm not sure what you mean by that. It was reported that:

> `if (content === "undefined")` is improper

And we are instead doing:

> `if (html === undefined)`

Which is equivalent to (assuming the `html` variable is actually defined):

> `if (typeof content == "undefined")`.

In fact I can't reproduce the issue you're talking about. What version of cash are you using?

**Comment by novns** [comment]
> In fact I can't reproduce the issue you're talking about. What version of cash are you using?

I use the latest `cash.min.js v1.0.0` available [here](https://kenwheeler.github.io/cash/)

**Comment by novns** [comment]
And the comparison is still `content === "undefined"` there.

**Comment by fabiospampinato** [comment]
That's so old switching to v4.1.5 will require significant efforts.

@kenwheeler I really think [this page](https://kenwheeler.github.io/cash/) should redirect to this repo.

**Comment by novns** [comment]
Thanks, I will try the new version.
