### ISSUE TITLE
Cannot set property length of #<HTMLCollection> which has only a getter

### ISSUE THREAD

**Issue by ndisidore** [kenwheeler/cash#72]
Error: Uncaught TypeError: Cannot set property length of #<HTMLCollection> which has only a getter(…)
OS: OSX El Capitan
Browser: Chrome 49

First: Thank you!
Having an issue when trying to interact with the DOM in the latest version of Chrome. See attached screenshot. Seems to be the case both when and individual node is selected or it has an array and across multiple functions.

Quick glance shows it coming from here:

```
cash.extend = fn.extend = function (target, source) {
    var prop;

    if (!source) {
      source = target;
      target = this;
    }

    for (prop in source) {
      if (source.hasOwnProperty(prop)) {
        target[prop] = source[prop];
      }
    }

    return target;
  };
```

![screen shot 2016-03-10 at 6 35 12 pm](https://cloud.githubusercontent.com/assets/1103087/13688286/d9dfb178-e6ee-11e5-8769-70ab9c71848f.png)

**Comment by ndisidore** [comment]
In short, it's trying to set the length property on the collection (which in this case is trying to say 3 = 0)

Quick and dirty fix: change line 16 of util.js to

`if ( args[i].hasOwnProperty(key) && 'length' !== prop ) { target[key] = args[i][key]; }`

**Comment by shshaw** [comment]
Strange. I'm testing in the same version of Chrome and can't quite replicate this with `getElementById` or `querySelectorAll` in this [codepen demo](https://github.com/kenwheeler/cash/issues/72). 

Two questions: 

1. Are you running the latest version of cash, 1.1.0? You can download it from [/dist](https://github.com/kenwheeler/cash/tree/master/dist). The CDN links and releases haven't been updated by @kenwheeler yet. 

2. What is the rest of your DOM structure?

**Comment by ndisidore** [comment]
Ahh yep, I think ya nailed it. I was using cash as pulled in by bower and from the looks of things bower is still pointing to 1.0.

```
bower cash#^1.0.0               cached git://github.com/kenwheeler/cash.git#1.0.0
bower cash#^1.0.0             validate 1.0.0 against git://github.com/kenwheeler/cash.git#^1.0.0
```

Updated CDNs would be awesome! Thanks for your help :+1: 
FYI: I'm using cash as part of this project (and that's where I hit this issue): https://github.com/ndisidore/SidneyGlass
