### ISSUE TITLE
Migrate Script?

### ISSUE THREAD

**Issue by petty** [kenwheeler/cash#75]
Not an issue, just an idea ...

What would make use of Cash (and other jQuery) alternatives a no brainer is the ability to temporarily add a library that console.warn'ed compatibility issues, like the one jQuery itself uses:

https://blog.jquery.com/2016/01/13/jquery-migrate-1-3-0-released/

**Comment by kenwheeler** [comment]
That would be dope. Any interest in helping with that?

**Comment by shvelo** [comment]
Seems interesting, do you mean warning about compatibility issues with jQuery? Or different versions of cash?

**Comment by shshaw** [comment]
Back before I merged halfDollar into cash, I had a super simple version of this:

```js
// Alert the dev if a collection function is not available.  
$.each('add addBack addClass after ajaxComplete ajaxError ajaxSend ajaxStart ajaxStop ajaxSuccess andSelf animate append appendTo attr before bind blur change children clearQueue click clone closest contents context css data dblclick delay delegate dequeue detach die empty end eq error fadeIn fadeOut fadeTo fadeToggle filter find finish first focus focusin focusout get has hasClass height hide hover html index innerHeight innerWidth insertAfter insertBefore is keydown keypress keyup last live load load map mousedown mouseenter mouseleave mousemove mouseout mouseover mouseup next nextAll nextUntil not off offset offsetParent on one outerHeight outerWidth parent parents parentsUntil position prepend prependTo prev prevAll prevUntil promise prop pushStack queue ready remove removeAttr removeClass removeData removeProp replaceAll replaceWith resize scroll scrollLeft scrollTop select selector serialize serializeArray show siblings size slice slideDown slideToggle slideUp stop submit text toArray toggle toggle toggleClass trigger triggerHandler unbind undelegate unload unwrap val width wrap wrapAll wrapInner'.split(' '),function(fn,i){
  if ( !$.fn[fn] ) { $.fn[fn] = function(){ console.warn('`.'+fn+'()` is not currently available. Try adding a cash.js extension, or switch to jQuery.'); return this; } }
});

// Alert the dev if a $ function is not available
$.each('ajax ajaxPrefilter ajaxSetup ajaxTransport boxModel browser Callbacks contains cssHooks cssNumber data Deferred dequeue error get getJSON getScript globalEval grep hasData holdReady inArray isArray isEmptyObject isFunction isNumeric isPlainObject isWindow isXMLDoc makeArray map merge noConflict noop now param parseHTML parseJSON parseXML post proxy queue removeData sub support trim type unique when boxModel browser'.split(' '),function(fn){
  if ( !$[fn] ) { $[fn] = function(){ console.warn('`.'+fn+'()` is not currently available. Try adding a cash.js extension, or switch to jQuery.'); return this; } }
});
```

Basically, it's a list of all the jQuery functions that cash loops through, and if it doesn't exist on the $ collection prototype it adds a console warning when the function is called.

**Comment by fabiospampinato** [comment]
As of v2.1.2 cash is much more aligned with jQuery, unless you're relying on features not available in cash, or relying on "obscure" jQuery behavior, you should be able to use cash as a drop-in replacement for jQuery.

**Comment by fabiospampinato** [comment]
There probably won't be a script for helping migrating from jQuery, the safest way to migrate from jQuery to cash is probably:

1. Make sure not to use any method/functionality not implemented in cash (ajax, animation, $.fn.slideToggle etc.)
2. Run jQuery's test suite with a patched version of jQuery where its collection methods have been replaced with cash's collection methods via `npm run test:jquery` and check if you rely on any functionality that didn't pass the tests.

I'm closing this in favor of the newly added `npm run test:jquery`.
