### ISSUE TITLE
Thief!

### ISSUE THREAD

**Issue by dthree** [kenwheeler/cash#76]
https://github.com/dthree/cash

:smile: 

Just kidding - this looks really cool!

Good luck!

**Comment by kenwheeler** [comment]
Hah I love your cash. I wrote this like 2 years ago, no idea why it's trending on HN lol.

**Comment by dthree** [comment]
Hey, thanks!

Oh snap - all your files had recent updates, so it made it look new.

I guess that makes me the thief!

**Comment by kenwheeler** [comment]
I think someone had it before us. We're both thieves!

**Comment by dthree** [comment]
That's what we get for picky such a good name. :smiling_imp:
