### ISSUE TITLE
isArray Example incorrect.

### ISSUE THREAD

**Issue by abusaidm** [kenwheeler/cash#78]
**###Currently**
$.isArray()
Check if the argument is an array.
$.isString([1,2,3]) // => true
**###Should be**
$.isArray()
Check if the argument is an array.
$.isArray([1,2,3]) // => true

**Comment by shvelo** [comment]
Fixed in Pull #81

**Comment by shshaw** [comment]
Pull #81 merged. Thanks, @shvelo!
