### ISSUE TITLE
Adding Collaborators

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#85]
There are quite a few issues that can be closed out ( #78, #55, #51, #48, #39, #15 ) and some simple pull requests that could be easily merged or closed ( #80, #79, #74, #57, #47 ). Since it's a busy time for you right now, it may be worthwhile to add a few collaborators to help manage the cash repo. @simeydotme, @thejameskyle and I have all contributed a good portion of the codebase for cash and could help you keep momentum going. What do you think?

**Comment by kenwheeler** [comment]
sure

**Comment by kenwheeler** [comment]
done

**Comment by shshaw** [comment]
Thanks! I'll clear out those outstanding items.
