### ISSUE TITLE
please setup ci

### ISSUE THREAD

**Issue by simbo** [kenwheeler/cash#86]
... for npm, bower and CDN.

As the ken wheeler himself [said](https://github.com/kenwheeler/cash/issues/73#issuecomment-200505753):
> Seriously though, I need to get CI set up and find some time to give it the hand test prior to a release.

Just wanted to make sure, this issue doesn't get lost... :)

**Comment by shshaw** [comment]
Thanks for carrying that over. CI setup is outside of my expertise, so I'll let @kenwheeler handle it.

**Comment by kenwheeler** [comment]
Ci is set up now

**Comment by kenwheeler** [comment]
It doesn't deploy to npm, bower and CDN. It just runs lint and test against the code. Deployment can come later.
