### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by simeydotme** [kenwheeler/cash#90]
Hey @kenwheeler @shshaw @thejameskyle , I noticed that the unit tests , specifically for `toggleClass` and `hasClass` as I worked on them, seem to be a little lack-lustre... ( see here for the tests I wrote which were not copied: https://github.com/kenwheeler/cash/pull/47/files#diff-c1129c8b045390789fa8ff62f2c6b4a9R50 )

I wonder if we should put a hold on adding / improving features until we've taken a run at improving testing... 

The recent growth for this library has been great and it's basically the core of any app that uses it... I think it's important to have extensive test suite in the inevitable situation where a bug is raised we have trouble to crack down on 😄 

I'll look at the class-related methods tonight ` and then spend some time to create a milestone/list of what other methods could use more rigorous tests; if everyone else agrees we should take a look at the tests :)

Best, Si.
- [x] implement **Karma / Mocha**
- [ ] add back tests for `hasClass`
- [ ] add back tests for `toggleClass`

**Comment by kenwheeler** [comment]
I'd personally like to move away from qunit and run a karma mocha suite instead. Anybody work with Ava? Worth trying instead of karma?

**Comment by kenwheeler** [comment]
welp, looks like ava doesn't run browsers like karma, so karma it is.

**Comment by shshaw** [comment]
I agree that testing could be improved, but I'm pretty inexperienced with that so I don't know that I can lend much help here. I tried to copy the existing tests' style and implement worthwhile checks, but I know some of them are a bit hacky.

In terms of new features or changes that need to happen are:
- [ ] Migrating from 6to5 to Babel for better ES6 conversion to fixing the global `"use strict";` ( #49 ) and help future proof the code
- [ ] `$.fn.wrap` and `$.fn.wrapInner`
- [ ] A migrate script ( #75 ), which I already have a basic version of.

I'll hold off on implementing anything while testing is revised, but are there any other big milestones that need to happen?

**Comment by kenwheeler** [comment]
I'd like to move off of gulp, use npm scripts instead, migrate to babel, implement a karma suite, get coverage reports and badge this shit up nicely.

**Comment by simeydotme** [comment]
- [ ] Implement Karma / Mocha

**Comment by simeydotme** [comment]
I'm gonna take a run at adding the tests, guys :)
I'll make a branch for it and share when I've gotten something review-able.

**Comment by simeydotme** [comment]
I just pushed a branch for collaborating on the #92 and #90 issues:
https://github.com/kenwheeler/cash/compare/npm-unit-tests

I've got Karma / Mocha running pretty well on my windows machine :tada: , with almost 30% coverage so far. ( also found a bug, raised at #100 )

But before going ahead to hit 100% I wanted to see if we can get a proper build working with **babel** and removing **gulp / qunit** completely.

@kenwheeler , if we're gonna try pairing on this it will have to be a weekend I guess, since I'm 12 hours ahead... But if that's no good then feel free to pull this branch and start removing **6to5** and fixing up the cash core to work with **babel** :smile:

**Comment by fabiospampinato** [comment]
I've added some `//TODO`s about methods without tests to [test/index.js](https://github.com/kenwheeler/cash/blob/master/test/index.js), if anybody wants to help improve our tests those todos might be a good starting point.

**Comment by fabiospampinato** [comment]
Closing this in favor of #192.
