### ISSUE TITLE
NPM scripts

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#92]
Move from Gulp to NPM Scripts

**Comment by simeydotme** [comment]
Depends on #90 to be completed.

**Comment by fibo** [comment]
Let me suggest the [this scripts](http://g14n.info/2015/12/tiny-npm-package/#packagejson), in particular the *postversion* hook and use of *pre-commit* and *npm-watch*.

**Comment by shshaw** [comment]
We could also ensure the build step is run pre-commit to be sure any changes make it into /dist/

**Comment by simeydotme** [comment]
NPM Scripts related to #90 #93  as part of an over-arching "build flow revision".
suggest checking out: https://github.com/kenwheeler/cash/tree/npm-unit-tests branch as a base for this improvement.

**Comment by simeydotme** [comment]
@kenwheeler , could you have a look at https://github.com/kenwheeler/cash/tree/npm-scripts ... I've got babel running there, and npm scripts with my unit tests... one thing that's annoying though:

**Adding a "header" banner to the file...**
I am completely lost how to grab the package contents from NPM scripts... it'll have top be a js/bash script, right? -- and then... how is that different to gulp?

**Comment by simeydotme** [comment]
Nevermind. I sorted it.
LOL. :joy:

**Comment by shshaw** [comment]
Switching to NPM scripts may make it difficult to implement custom build modularity ( issue #94 ) to Cash. Any thoughts on how we could implement that in the new build system?

**Comment by simeydotme** [comment]
Actually, Preprocess should be able to run from NPM Scripts. I even tried it... however; the `preprocess-cli` wrapper for `preprocess` seems broken/out of date... and just plain fails to install. If that was working there's not to use it.

Currently I've just got a single script concatenating all the files.

I, Personally, don't want to get in to complicated piping and argv handling, as I really think anything that complicated should be in a `.js` (gulp or otherwise) or .`sh` file

**Comment by shshaw** [comment]
Agreed. I'd like it to be as simple as possible, but would still like to see custom build functionality. Any other libraries out there that do something similar?

**Comment by fibo** [comment]
You can do a lot of things with npm scripts like using glob, launch other npm scripts in sequence, even for loops [like this](https://github.com/fibo/dflow/blob/master/package.json#L46).

They are easier than .js or .sh or gulp/grunt, cause they are just commands that you launch and store in a single row.

Concat files should be as easy as `cat src/*js > build/${npm_package_name}.js` however there can be some use cases where it is better to use scripts. In that case, usually I create a *src/npm-scripts/* folder.

**Comment by fabiospampinato** [comment]
As of v2.1.2 Gulp tasks have been replaced with NPM scripts + [pacco](https://github.com/fabiospampinato/pacco).
