### ISSUE TITLE
Migrate to Babel

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#93]
Migrating from 6to5 to Babel for better ES6 conversion to fixing the global "use strict"; ( #49 ) and help future proof the code

**Comment by shshaw** [comment]
I attempted this using the Babel "ES2015" preset, and it looks like it has quite a few Babel plugins that aren't necessary and add cruft or keep the global `"use strict";`

Here's the list from `/node_modules/babel-preset-es2015/index.js`, with the unnecessary modules commented out.

```
module.exports = {
  plugins: [
    require("babel-plugin-transform-es2015-template-literals"),
    require("babel-plugin-transform-es2015-literals"),
    //require("babel-plugin-transform-es2015-function-name"),
    require("babel-plugin-transform-es2015-arrow-functions"),
    require("babel-plugin-transform-es2015-block-scoped-functions"),
    require("babel-plugin-transform-es2015-classes"),
    require("babel-plugin-transform-es2015-object-super"),
    require("babel-plugin-transform-es2015-shorthand-properties"),
    require("babel-plugin-transform-es2015-duplicate-keys"),
    require("babel-plugin-transform-es2015-computed-properties"),
    require("babel-plugin-transform-es2015-for-of"),
    require("babel-plugin-transform-es2015-sticky-regex"),
    require("babel-plugin-transform-es2015-unicode-regex"),
    require("babel-plugin-check-es2015-constants"),
    require("babel-plugin-transform-es2015-spread"),
    require("babel-plugin-transform-es2015-parameters"),
    require("babel-plugin-transform-es2015-destructuring"),
    require("babel-plugin-transform-es2015-block-scoping"),
    //require("babel-plugin-transform-es2015-typeof-symbol"),
    //require("babel-plugin-transform-es2015-modules-commonjs"),
    [require("babel-plugin-transform-regenerator"), { async: false, asyncGenerators: false }],
  ]
};
```

There are probably a lot of those that aren't strictly necessary either, so we could probably avoid using the preset altogether and require a few specific plugins. Based on the current code I think these may be the only ones necessary:

* babel-plugin-transform-es2015-arrow-functions
* babel-plugin-transform-es2015-block-scoped-functions
* babel-plugin-transform-es2015-template-literals

**Comment by simeydotme** [comment]
Migrate to babel related to #90 #92 as part of an over-arching "build flow revision".
suggest checking out: https://github.com/kenwheeler/cash/tree/npm-unit-tests branch as a base for this improvement.

**Comment by simeydotme** [comment]
@shshaw did you want to handle this completely? :)
If so, go ahead and assign yourself and check out the https://github.com/kenwheeler/cash/tree/npm-scripts branch as a base... that's the one I'm working on for unit tests and npm-scripts, it has babel running, too :)

**Comment by shshaw** [comment]
I don't have that much experience with Babel or ES2015 in general, so if anyone else does they would be much better qualified to set all of that up! My notes from above are just what I could suss out from the horrible-for-beginners Babel documentation.

**Comment by simeydotme** [comment]
Yes, it's pretty bad.

Ok, well since I'm sorting out the unit tests in that branch, I'll take care of this for now. I'm not going to change the code, or style, at this moment. That can be another workflow enhancement in the future (`eslint-babel`, perhaps). 

Thanks for the effort on dissecting which modules are useful :)

**Comment by shshaw** [comment]
Took another stab at this, and managed a gulp-free build process using babel and uglify.

Pushed to the [build-revision](https://github.com/kenwheeler/cash/tree/build-revision) branch.

**Comment by fabiospampinato** [comment]
As of v2.1.2 we now use Babel.
