### ISSUE TITLE
Version Numbering

### ISSUE THREAD

**Issue by shshaw** [kenwheeler/cash#97]
Recommendation: We should use the [Semantic Versioning](http://semver.org/) method of tagging release versions, mostly summed up thusly:

>Given a version number MAJOR.MINOR.PATCH, increment the:
> * MAJOR version when you make incompatible API changes,
> * MINOR version when you add functionality in a backwards-compatible manner, and
> * PATCH version when you make backwards-compatible bug fixes.

So patch version for bug fixes, minor version bump for feature additions, major for significant changes that may break how people currently use cash (removing ajax, etc.).

Agreed?

**Comment by simeydotme** [comment]
@shshaw ... minor is for public feature additions, correct?
Adding tests / npm scripts would not be a minor bump, correct?

**Comment by shshaw** [comment]
I believe you are correct.

**Comment by shshaw** [comment]
Looks like everyone's on board. I'll close this down, but we can talk about it more if need be.
