### ISSUE TITLE
Function .first() not returning element

### ISSUE THREAD

**Issue by lgraubner** [kenwheeler/cash#98]
I have a collection containing one element. To get the element I'm using `.first()` and expect to get the element back. Instead it returns the same collection.

**Comment by lgraubner** [comment]
Nvm, misunderstood docs.

**Comment by shshaw** [comment]
Sounds like you figured it out, but to clarify: `.first()`, `.eq()` and `.last()` all return collections, not raw DOM elements. `.get()` would be the method you're looking for! 

Alternatively, you can treat the collection like an array and use `$('div')[0]` to get the first element.

**Comment by lgraubner** [comment]
Already figured that out. `.get(0)` is basicly the same, right?
