### ISSUE TITLE
Add ajax functions.

### ISSUE THREAD

**Issue by lukashl** [kenwheeler/cash#99]
Hello

Great works, good library. One thing i need more is ajax suport ...

**Comment by simeydotme** [comment]
@lukashl please do a search for issues before creating one :)

**Comment by shshaw** [comment]
Refer specifically to issue #15 for suggested libraries.

**Comment by lukashl** [comment]
ups, i miss

maybe add ajax as aditional patch to choose ?

**Comment by shshaw** [comment]
@lukashl In the interest of keeping cash lightweight and focused on the DOM, AJAX functionality is probably not going to be added in again unless @kenwheeler decides otherwise.

**Comment by kenwheeler** [comment]
I mean why would you. There is first class support nowadays via fetch.

**Comment by kenwheeler** [comment]
or if you want a lib theres always request, superagent, axios
